// ==UserScript==
// @version     1.0.0
// @copyright   2018+, Robin Findley
// ==/UserScript==

// Console code to fetch details:
//var klist = '孜宏幌弘彦旭曽李梶浩渕煕盧磯菱亘亨伍俣倶其冨函劉厘哨喬圭堺妖姜寅峻崔嶋嶌嶺巌幡慌挫捉敦晃晋柏柿栗桂桐椿楊楠榎槙樋樺樽毅洲淳淵湘灘猪獅玲琵琶瓦畠畿痕磐祐秦稔窪笹筑篠粕紘聯肇腎芥芦茅荻萩葛蒲薩薫蘇蘭袖諏趙辰辻逓郁鄭釜釧雀霞鴨鵬鷲鷹麹丑串乞仇伽佃但佑侠侯倣倭偕偲僑儒儲允兜冤冥冴凄凧凱剃剥勅匂匡卯卿厦厨叢叩只叶吊呑咸啄喉喋喘喧嗅嗜嗣嘘噂噛噺嚇囃坐埴堆塙壕壬壱壷夷奄姑姚娼嫉嫡嬉孟宋宍宕宵寓尖尭尹屏峙峨峯嵯嶽已巳巴巷巽帖庵廟廣弛彗彪彬彭徘怜怨恣悌惇惚惟惣惧愁慧或抄抒拭挨挺捧揃搜摯撚撫播斑斥於旛旺暉暢曼朋朔杖杜杞杭杵柚桝桧桶梁梯棺椙楕楢楼榊榛槌槍槻樟樫橘橿檀檄檜櫛欣欽此歪毬汎汐汪洒洛洸浙淘渚渥湊湛溜溢溥漕漱澤濡瀋瀕炒焉煎煥燈燕牌牝牟牡牢犀狛狸狼猷玩珂琉琢甕甦甫畏畝瘤癌皐皓眉眞瞑矩砦硝硯碓碧礒祇禄禎稀稜稽穣窯竪竿笏笘箏箕篆篇篭簑簗粟粥糞絆絢綜綴緻縞繕繭罵翁翠翫耀股肢胚脩腫膝膠膳臼舘舛舜舩舵艶芙芭芹苅苑苫茗荏菩萬萱葦蒋蒔蓋蓼蔡蔦蔭蕃蕉蕨薔薪薮藁藏藝蚕蛋蛭蜷衷袁袴裾褐襄訃詔詫諌諜諦謄謳讃貰賜贋赳蹄蹴轍轟迦逐逗逢邑鄒酉醍釘鉾銕銚錫鍼鍾闊附隈雁雛雫鞍韮韻頒頚頬餅餌饗馨魁魏魯鮎鮫鮭鯛鱒鱗鳳鴈鴎鴻鵜鵠鷺麓麺黎黛';
//function toarr(s) {return s.replace(/(^\s+|\s+$)/g,'').replace(/'/g,'\\\'').replace(/\s*[,、]\s*/g,',').split(',');}
//function clean_yomi(s) {return s.replace(/\..*/g,'');}
//Promise.all(klist.split('').map(kanji => {
//    return $.get('https://jisho.org/search/%23kanji%20'+kanji).then(content => {
//        let html = $(content);
//        let meanings = toarr(html.find('.kanji-details__main-meanings').text());
//        let onyomi = toarr(html.find('.on_yomi .kanji-details__main-readings-list').text()).map(clean_yomi);
//        let kunyomi = toarr(html.find('.kun_yomi .kanji-details__main-readings-list').text()).map(clean_yomi);
//        return '        \''+kanji+'\': {'+
//            'meanings:[\''+meanings.join('\',\'')+'\'], '+
//            'kunyomi:[\''+kunyomi.join('\',\'')+'\'], '+
//            'onyomi:[\''+onyomi.join('\',\'')+'\']},';
//    });
//})).then(results => {
//    results.sort((a,b) => a[9].localeCompare(b[9]));
//    console.log(results.join('\n'));
//});

(function (gobj) {
  if (!gobj.freq) gobj.freq = {};

  let freq = gobj.freq;

  freq.kanji_by_freq =
    "日一国会人年大十二本中長出三同時政事自行社見月分議後前民生連五発間対上部東者党地合市業内相方四定今回新場金員九入選立開手米力学問高代明実円関決子動京全目表戦経通外最言氏現理調体化田当八六約主題下首意法不来作性的要用制治度務強気小七成期公持野協取都和統以機平総加山思家話世受区領多県続進正安設保改数記院女初北午指権心界支第産結百派点教報済書府活原先共得解名交資予川向際査勝面委告軍文反元重近千考判認画海参売利組知案道信策集在件団別物側任引使求所次水半品昨論計死官増係感特情投示変打男基私各始島直両朝革価式確村提運終挙果西勢減台広容必応演電歳住争談能無再位置企真流格有疑口過局少放税検藤町常校料沢裁状工建語球営空職証土与急止送援供可役構木割聞身費付施切由説転食比難防補車優夫研収断井何南石足違消境神番規術護展態導鮮備宅害配副算視条幹独警宮究育席輸訪楽起万着乗店述残想線率病農州武声質念待試族象銀域助労例衛然早張映限親額監環験追審商葉義伝働形景落欧担好退準賞訴辺造英被株頭技低毎医復仕去姿味負閣韓渡失移差衆個門写評課末守若脳極種美岡影命含福蔵量望松非撃佐核観察整段横融型白深字答夜製票況音申様財港識注呼渉達良響阪帰針専推谷古候史天階程満敗管値歌買突兵接請器士光討路悪科攻崎督授催細効図週積丸他及湾録処省旧室憲太橋歩離岸客風紙激否周師摘材登系批郎母易健黒火戸速存花春飛殺央券赤号単盟座青破編捜竹除完降超責並療従右修捕隊危採織森競拡故館振給屋介読弁根色友苦就迎走販園具左異歴辞将秋因献厳馬愛幅休維富浜父遺彼般未塁貿講邦舞林装諸夏素亡劇河遣航抗冷模雄適婦鉄寄益込顔緊類児余禁印逆王返標換久短油妻暴輪占宣背昭廃植熱宿薬伊江清習険頼僚覚吉盛船倍均億途圧芸許皇臨踏駅署抜壊債便伸留罪停興爆陸玉源儀波創障継筋狙帯延羽努固闘精則葬乱避普散司康測豊洋静善逮婚厚喜齢囲卒迫略承浮惑崩順紀聴脱旅絶級幸岩練押軽倒了庁博城患締等救執層版老令角絡損房募曲撤裏払削密庭徒措仏績築貨志混載昇池陣我勤為血遅抑幕居染温雑招奈季困星傷永択秀著徴誌庫弾償刊像功拠香欠更秘拒刑坂刻底賛塚致抱繰服犯尾描布恐寺鈴盤息宇項喪伴遠養懸戻街巨震願絵希越契掲躍棄欲痛触邸依籍汚縮還枚属笑互複慮郵束仲栄札枠似夕恵板列露沖探逃借緩節需骨射傾届曜遊迷夢巻購揮君燃充雨閉緒跡包駐貢鹿弱却端賃折紹獲郡併草徹飲貴埼衝焦奪雇災浦暮替析預焼簡譲称肉納樹挑章臓律誘紛貸至宗促慎控贈智握照宙酒俊銭薄堂渋群銃悲秒操携奥診詰託晴撮誕侵括掛謝双孝刺到駆寝透津壁稲仮暗裂敏鳥純是飯排裕堅訳盗芝綱吸典賀扱顧弘看訟戒祉誉歓勉奏勧騒翌陽閥甲快縄片郷敬揺免既薦隣悩華泉御範隠冬徳皮哲漁杉里釈己荒貯硬妥威豪熊歯滞微隆埋症暫忠倉昼茶彦肝柱喚沿妙唱祭袋阿索誠忘襲雪筆吹訓懇浴俳童宝柄驚麻封胸娘砂李塩浩誤剤瀬趣陥斎貫仙慰賢序弟旬腕兼聖旨即洗柳舎偽較覇兆床畑慣詳毛緑尊抵脅祝礼窓柔茂犠旗距雅飾網竜詩昔繁殿濃翼牛茨潟敵魅嫌魚斉液貧敷擁衣肩圏零酸兄罰怒滅泳礎腐祖幼脚菱荷潮梅泊尽杯僕桜滑孤黄煕炎賠句寿鋼頑甘臣鎖彩摩浅励掃雲掘縦輝蓄軸巡疲稼瞬捨皆砲軟噴沈誇祥牲秩帝宏唆鳴阻泰賄撲凍堀腹菊絞乳煙縁唯膨矢耐恋塾漏紅慶猛芳懲郊剣腰炭踊幌彰棋丁冊恒眠揚冒之勇曽械倫陳憶怖犬菜耳潜珍梨仁克岳概拘墓黙須偏雰卵遇湖諮狭喫卓干頂虫刷亀糧梶湯箱簿炉牧殊殖艦溶輩穴奇慢鶴謀暖昌拍朗丈鉱寛覆胞泣涙隔浄匹没暇肺孫貞靖鑑飼陰銘鋭随烈尋渕稿枝丹啓也丘棟壌漫玄粘悟舗妊塗熟軒旭恩毒騰往豆遂晩狂叫栃岐陛緯培衰艇屈径淡抽披廷錦准暑拝磯奨妹浸剰胆氷繊駒乾虚棒寒孜霊帳悔諭祈惨虐翻墜沼据肥徐糖搭姉髪忙盾脈滝拾軌俵妨盧粉擦鯨漢糸荘諾雷漂懐勘綿栽才拐笠駄添汗冠斜銅鏡聡浪亜覧詐壇勲魔酬紫湿曙紋卸奮趙欄逸涯拓眼瓶獄筑尚阜彫咲穏顕巧矛垣召欺釣缶萩粧隻葛脂粛栗愚蒸嘉遭架篠鬼庶肌稚靴菅滋幻煮姫誓耕把践呈疎仰鈍恥剛疾征砕謡嫁謙后嘆俣菌鎌巣泥頻琴班淵棚潔酷宰廊寂辰隅偶霞伏灯柏辛磨碁俗漠邪晶辻麦墨鎮洞履劣那殴娠奉憂朴亭姓淳荻筒鼻嶋怪粒詞鳩柴偉酔惜穫佳潤悼乏胃該赴桑桂髄虎盆晋穂壮堤飢傍疫累痴搬畳晃癒桐寸郭机尿凶吐宴鷹賓虜膚陶鐘憾畿猪紘磁弥昆粗訂芽尻庄傘敦騎寧濯循忍磐猫怠如寮祐鵬塔沸鉛珠凝苗獣哀跳灰匠菓垂蛇澄縫僧幾眺唐亘呉凡憩鄭芦龍媛溝恭刈睡錯伯帽笹穀柿陵霧魂枯弊釧妃舶餓腎窮掌麗綾臭釜悦刃縛暦宜盲粋辱毅轄猿弦嶌稔窒炊洪摂飽函冗涼桃狩舟貝朱渦紳枢碑鍛刀鼓裸鴨符猶塊旋弓幣膜扇脇腸憎槽鍋慈皿肯樋楊伐駿漬燥糾亮墳坪畜紺慌娯吾椿舌羅坊峡俸厘峰圭醸蓮弔乙倶汁尼遍堺衡呆薫瓦猟羊窪款閲雀偵喝敢畠胎酵憤豚遮扉硫赦挫挟窃泡瑞又慨紡恨肪扶戯伍忌濁奔斗蘭蒲迅肖鉢朽殻享秦茅藩沙輔曇媒鶏禅嘱胴粕冨迭挿湘嵐椎灘堰獅姜絹陪剖譜郁悠淑帆暁鷲傑楠笛芥其玲奴誰錠拳翔遷拙侍尺峠篤肇渇榎俺劉幡諏叔雌亨堪叙酢吟逓痕嶺袖甚喬崔妖琵琶聯蘇闇崇漆岬癖愉寅捉礁乃洲屯樽樺槙薩姻巌淀麹賭擬塀唇睦閑胡幽峻曹哨詠炒屏卑侮鋳抹尉槻隷禍蝶酪茎汎頃帥梁逝滴汽謎琢箕匿爪芭逗苫鍵襟蛍楢蕉兜寡琉痢庸朋坑姑烏藍僑賊搾奄臼畔遼唄孔橘漱呂桧拷宋嬢苑巽杜渓翁藝廉牙謹瞳湧欣窯褒醜魏篇升此峯殉煩巴禎枕劾菩堕丼租檜稜牟桟榊錫荏惧倭婿慕廟銚斐罷矯某囚魁薮虹鴻泌於赳漸逢凧鵜庵膳蚊葵厄藻萬禄孟鴈狼嫡呪斬尖翫嶽尭怨卿串已嚇巳凸暢腫粟燕韻綴埴霜餅魯硝牡箸勅芹杏迦棺儒鳳馨斑蔭焉慧祇摯愁鷺楼彬袴匡眉苅讃尹欽薪湛堆狐褐鴎瀋挺賜嵯雁佃綜繕狛壷橿栓翠鮎芯蜜播榛凹艶帖伺桶惣股匂鞍蔦玩萱梯雫絆錬湊蜂隼舵渚珂煥衷逐斥稀癌峨嘘旛篭芙詔皐雛娼篆鮫椅惟牌宕喧佑蒋樟耀黛叱櫛渥挨憧濡槍宵襄妄惇蛋脩笘宍甫酌蚕壕嬉囃蒼餌簗峙粥舘銕鄒蜷暉捧頒只肢箏檀鵠凱彗謄諌樫噂脊牝梓洛醍砦丑笏蕨噺抒嗣隈叶凄汐絢叩嫉朔蔡膝鍾仇伽夷恣瞑畝抄杭寓麺戴爽裾黎惰坐鍼蛮塙冴旺葦礒咸萌饗歪冥偲壱瑠韮漕杵薔膠允眞蒙蕃呑侯碓茗麓瀕蒔鯉竪弧稽瘤澤溥遥蹴或訃矩厦冤剥舜侠贅杖蓋畏喉汪猷瑛搜曼附彪撚噛卯桝撫喋但溢闊藏浙彭淘剃揃綺徘巷竿蟹芋袁舩拭茜凌頬厨犀簑皓甦洸毬檄姚蛭婆叢椙轟贋洒貰儲緋貼諜鯛蓼甕喘怜溜邑鉾倣碧燈諦煎瓜緻哺槌啄穣嗜偕罵酉蹄頚胚牢糞悌吊楕鮭乞倹嗅詫鱒蔑轍醤惚廣藁柚舛縞謳杞鱗繭釘弛狸壬硯";
  freq.kanji_details = {
    丑: {
      meanings: ["sign of the ox or cow", "1-3AM", "second sign of Chinese zodiac"],
      kunyomi: ["うし"],
      onyomi: ["チュウ"],
    },
    串: { meanings: ["spit", "skewer"], kunyomi: ["くし", "つらぬ"], onyomi: ["カン", "ケン", "セン"] },
    乞: { meanings: ["beg", "invite", "ask"], kunyomi: ["こ"], onyomi: ["コツ", "キツ", "キ", "キケ", "コチ"] },
    亘: { meanings: ["span", "range", "extend over"], kunyomi: ["わた", "もと"], onyomi: ["コウ", "カン", "セン"] },
    亨: { meanings: ["pass through", "go smoothly"], kunyomi: ["とお"], onyomi: ["コウ", "キョウ", "ホウ"] },
    仇: {
      meanings: ["foe", "enemy", "revenge", "grudge", "feud"],
      kunyomi: ["あだ", "あた", "かたき", "つれあい"],
      onyomi: ["キュウ", "グ"],
    },
    伍: { meanings: ["five", "five-man squad", "file", "line"], kunyomi: ["いつつ"], onyomi: ["ゴ"] },
    伽: { meanings: ["nursing", "attending", "entertainer"], kunyomi: ["とぎ"], onyomi: ["カ", "ガ", "キャ", "ギャ"] },
    佃: { meanings: ["cultivated rice field"], kunyomi: ["つくだ"], onyomi: ["テン", "デン"] },
    但: { meanings: ["however", "but"], kunyomi: ["ただ"], onyomi: ["タン"] },
    佑: { meanings: ["help", "assist"], kunyomi: ["たす"], onyomi: ["ユウ", "ウ"] },
    侠: { meanings: ["tomboy", "chivalry"], kunyomi: ["きゃん", "おとこだて"], onyomi: ["キョウ"] },
    侯: { meanings: ["marquis", "lord", "daimyo"], kunyomi: [""], onyomi: ["コウ"] },
    俣: { meanings: ["crotch", "thigh", "groin", "(kokuji)"], kunyomi: ["また"], onyomi: [""] },
    倣: { meanings: ["emulate", "imitate"], kunyomi: ["なら"], onyomi: ["ホウ"] },
    倭: { meanings: ["Yamato", "ancient Japan"], kunyomi: ["やまと", "したが"], onyomi: ["ワ", "イ"] },
    倶: { meanings: ["both"], kunyomi: ["とも"], onyomi: ["グ", "ク"] },
    偕: { meanings: ["together"], kunyomi: ["ともに"], onyomi: ["カイ"] },
    偲: { meanings: ["recollect", "remember"], kunyomi: ["しの"], onyomi: ["サイ", "シ"] },
    僑: { meanings: ["temporary home"], kunyomi: [""], onyomi: ["キョウ"] },
    儒: { meanings: ["Confucian"], kunyomi: [""], onyomi: ["ジュ"] },
    儲: {
      meanings: ["be profitable", "yield profit"],
      kunyomi: ["もう", "もう", "もうけ", "たくわ"],
      onyomi: ["チョ"],
    },
    允: { meanings: ["license", "sincerity", "permit"], kunyomi: ["じょう", "まこと", "ゆるす"], onyomi: ["イン"] },
    兜: { meanings: ["helmet", "head piece"], kunyomi: ["かぶと"], onyomi: ["トウ", "ト"] },
    其: { meanings: ["that"], kunyomi: ["それ", "その"], onyomi: ["キ", "ギ", "ゴ"] },
    冤: { meanings: ["false charge", "hatred"], kunyomi: [""], onyomi: ["エン"] },
    冥: { meanings: ["dark"], kunyomi: ["くら"], onyomi: ["メイ", "ミョウ"] },
    冨: { meanings: ["enrich", "wealthy", "abundant"], kunyomi: ["と", "とみ"], onyomi: ["フ", "フウ"] },
    冴: { meanings: ["be clear", "serene", "cold", "skilful"], kunyomi: ["さ", "こお", "ひ"], onyomi: ["ゴ", "コ"] },
    凄: {
      meanings: ["uncanny", "weird", "threatening", "horrible"],
      kunyomi: ["さむ", "すご", "すさ"],
      onyomi: ["セイ", "サイ"],
    },
    凧: { meanings: ["kite", "(kokuji)"], kunyomi: ["いかのぼり", "たこ"], onyomi: [""] },
    凱: { meanings: ["victory song"], kunyomi: ["かちどき", "やわらぐ"], onyomi: ["ガイ", "カイ"] },
    函: { meanings: ["box (archaic)"], kunyomi: ["はこ", "い"], onyomi: ["カン"] },
    剃: { meanings: ["shave"], kunyomi: ["まい", "そ", "す"], onyomi: ["テイ"] },
    剥: {
      meanings: ["come off", "peel", "fade", "discolor"],
      kunyomi: ["へ", "へず", "む", "む", "は", "は", "は", "は"],
      onyomi: ["ハク", "ホク"],
    },
    劉: {
      meanings: [
        "weapon of war",
        "logging axe",
        "kill en masse",
        "peeling (paint off a wall",
        "etc)",
        "sparse",
        "faded",
      ],
      kunyomi: ["ころ"],
      onyomi: ["リュウ", "ル"],
    },
    勅: { meanings: ["imperial order"], kunyomi: ["いまし", "みことのり"], onyomi: ["チョク"] },
    匂: {
      meanings: ["fragrant", "stink", "glow", "insinuate", "(kokuji)"],
      kunyomi: ["にお", "にお", "にお"],
      onyomi: [""],
    },
    匡: { meanings: ["correct", "save", "assist"], kunyomi: ["すく"], onyomi: ["キョウ", "オウ"] },
    卯: {
      meanings: ["sign of the hare or rabbit", "fourth sign of Chinese zodiac", "5-7AM", "east"],
      kunyomi: ["う"],
      onyomi: ["ボウ", "モウ"],
    },
    卿: { meanings: ["you", "lord", "secretary", "state minister"], kunyomi: ["きみ"], onyomi: ["ケイ", "キョウ"] },
    厘: { meanings: ["rin", "1/10 sen", "1/10 bu"], kunyomi: [""], onyomi: ["リン"] },
    厦: { meanings: ["house"], kunyomi: ["いえ"], onyomi: ["カ", "サ"] },
    厨: { meanings: ["kitchen"], kunyomi: ["くりや"], onyomi: ["シュウ", "ズ", "チュ", "チュウ"] },
    叢: {
      meanings: ["plexus", "clump of bushes", "thicket"],
      kunyomi: ["くさむら", "むら", "むら"],
      onyomi: ["ソウ", "ス"],
    },
    叩: {
      meanings: ["strike", "beat", "kow tow", "hit", "thrash", "criticize"],
      kunyomi: ["たた", "はた", "すぎ"],
      onyomi: ["コウ"],
    },
    只: { meanings: ["only", "free", "in addition"], kunyomi: ["ただ"], onyomi: ["シ"] },
    叶: { meanings: ["grant", "answer"], kunyomi: ["かな", "かな"], onyomi: ["キョウ"] },
    吊: { meanings: ["suspend", "hang", "wear (sword)"], kunyomi: ["つ", "つる"], onyomi: ["チョウ"] },
    呑: { meanings: ["drink"], kunyomi: ["の"], onyomi: ["トン", "ドン"] },
    咸: { meanings: ["all", "same"], kunyomi: [""], onyomi: ["カン", "ゲン"] },
    哨: { meanings: ["scout", "sentinel"], kunyomi: ["みはり"], onyomi: ["ショウ"] },
    啄: { meanings: ["peck", "pick up"], kunyomi: ["ついば", "つつ"], onyomi: ["タク", "ツク", "トク"] },
    喉: { meanings: ["throat", "voice"], kunyomi: ["のど"], onyomi: ["コウ"] },
    喋: { meanings: ["talk", "chat", "chatter"], kunyomi: ["しゃべ", "ついば"], onyomi: ["チョウ", "トウ"] },
    喘: { meanings: ["pant", "gasp", "breathe hard"], kunyomi: ["あえ", "せき"], onyomi: ["ゼン", "セン"] },
    喧: { meanings: ["noisy", "boisterous"], kunyomi: ["やかま", "かまびす"], onyomi: ["ケン"] },
    喬: { meanings: ["high", "boasting"], kunyomi: ["たか"], onyomi: ["キョウ"] },
    嗅: { meanings: ["smell", "sniff", "scent"], kunyomi: ["か"], onyomi: ["キュウ"] },
    嗜: { meanings: ["like", "taste", "modest"], kunyomi: ["たしな", "たしな", "この", "この"], onyomi: ["シ"] },
    嗣: { meanings: ["heir", "succeed"], kunyomi: [""], onyomi: ["シ"] },
    嘘: { meanings: ["lie", "falsehood"], kunyomi: ["うそ", "ふ"], onyomi: ["キョ", "コ"] },
    噂: { meanings: ["rumor", "gossip", "hearsay"], kunyomi: ["うわさ"], onyomi: ["ソン"] },
    噛: { meanings: ["chew", "bite", "gnaw"], kunyomi: ["か", "か"], onyomi: ["コウ", "ゴウ"] },
    噺: { meanings: ["talk", "(kokuji)"], kunyomi: ["はなし"], onyomi: [""] },
    嚇: { meanings: ["menacing", "dignity", "majesty", "threaten"], kunyomi: ["おど"], onyomi: ["カク"] },
    囃: {
      meanings: ["play (music)", "accompany", "beat time", "banter", "jeer", "applaud"],
      kunyomi: ["はや", "はやし"],
      onyomi: ["サツ", "ソウ"],
    },
    圭: { meanings: ["square jewel", "corner", "angle", "edge"], kunyomi: [""], onyomi: ["ケイ", "ケ"] },
    坐: { meanings: ["sit"], kunyomi: ["すわ", "おわす", "そぞろに", "まします"], onyomi: ["ザ", "サ"] },
    埴: { meanings: ["clay"], kunyomi: ["はに", "へな"], onyomi: ["ショク"] },
    堆: { meanings: ["piled high"], kunyomi: ["うずたか"], onyomi: ["タイ", "ツイ"] },
    堺: { meanings: ["world"], kunyomi: ["さかい"], onyomi: ["カイ"] },
    塙: { meanings: ["projecting tableland or mountain"], kunyomi: ["はなわ", "かた"], onyomi: ["カク", "コウ"] },
    壕: { meanings: ["trench", "dugout", "air raid shelter"], kunyomi: ["ほり"], onyomi: ["コウ", "ゴウ"] },
    壬: { meanings: ["9th calendar sign"], kunyomi: ["みずのえ"], onyomi: ["ニン", "ジン", "イ"] },
    壱: { meanings: ["one (in documents)"], kunyomi: ["ひとつ"], onyomi: ["イチ", "イツ"] },
    壷: { meanings: ["jar", "pot", "hinge knuckle", "one's aim"], kunyomi: ["つぼ"], onyomi: ["コ"] },
    夷: { meanings: ["barbarian", "savage", "Ainu"], kunyomi: ["えびす", "えみし", "ころ", "たい"], onyomi: ["イ"] },
    奄: { meanings: ["cover", "suffocate", "obstruct"], kunyomi: ["おお", "たちまち"], onyomi: ["エン"] },
    妖: { meanings: ["attractive", "bewitching", "calamity"], kunyomi: ["あや", "なま", "わざわ"], onyomi: ["ヨウ"] },
    姑: { meanings: ["mother-in-law"], kunyomi: ["しゅうとめ", "しゅうと", "おば", "しばらく"], onyomi: ["コ"] },
    姚: { meanings: ["beautiful"], kunyomi: ["うつく"], onyomi: ["ヨウ", "チョウ"] },
    姜: { meanings: ["Chinese surname", "ginger"], kunyomi: ["こう"], onyomi: ["キョウ", "ガ"] },
    娼: { meanings: ["prostitute"], kunyomi: ["あそびめ"], onyomi: ["ショウ"] },
    嫉: { meanings: ["jealous", "envy"], kunyomi: ["そね", "ねた", "にく"], onyomi: ["シツ"] },
    嫡: { meanings: ["legitimate wife", "direct descent (non-bastard)"], kunyomi: [""], onyomi: ["チャク", "テキ"] },
    嬉: { meanings: ["glad", "pleased", "rejoice"], kunyomi: ["うれ", "たの"], onyomi: ["キ"] },
    孜: { meanings: ["industriousness"], kunyomi: ["つと"], onyomi: ["シ"] },
    孟: { meanings: ["chief", "beginning"], kunyomi: ["かしら"], onyomi: ["モウ", "ボウ", "ミョウ"] },
    宋: { meanings: ["dwell", "Sung dynasty"], kunyomi: [""], onyomi: ["ソウ"] },
    宍: { meanings: ["muscles", "meat"], kunyomi: ["しし"], onyomi: ["ニク", "ジク"] },
    宏: { meanings: ["wide", "large"], kunyomi: ["ひろ"], onyomi: ["コウ"] },
    宕: { meanings: ["cave"], kunyomi: ["すぎる"], onyomi: ["トウ"] },
    宵: { meanings: ["wee hours", "evening", "early night"], kunyomi: ["よい"], onyomi: ["ショウ"] },
    寅: {
      meanings: ["sign of the tiger", "3-5AM", "third sign of Chinese zodiac"],
      kunyomi: ["とら"],
      onyomi: ["イン"],
    },
    寓: {
      meanings: ["temporary abode", "imply", "suggest"],
      kunyomi: ["ぐう", "かこつ", "よ", "よ", "かりずまい"],
      onyomi: ["グウ", "グ", "ドウ"],
    },
    尖: {
      meanings: ["be pointed", "sharp", "taper", "displeased", "angry", "edgy"],
      kunyomi: ["とが", "さき", "するど"],
      onyomi: ["セン"],
    },
    尭: { meanings: ["high", "far"], kunyomi: ["たか"], onyomi: ["ギョウ"] },
    尹: { meanings: ["an official rank"], kunyomi: ["おさ", "ただ"], onyomi: ["イン"] },
    屏: { meanings: ["wall", "fence"], kunyomi: ["おお", "しりぞ", "びょう"], onyomi: ["ヘイ", "ビョウ"] },
    峙: { meanings: ["tower", "soar"], kunyomi: ["そばだ"], onyomi: ["ジ"] },
    峨: { meanings: ["high mountain"], kunyomi: ["けわ"], onyomi: ["ガ"] },
    峯: { meanings: ["peak", "summit"], kunyomi: ["みね", "ね"], onyomi: ["ホウ"] },
    峻: { meanings: ["high", "steep"], kunyomi: ["けわ", "たか"], onyomi: ["シュン"] },
    崔: { meanings: ["cliff", "bluff", "precipice"], kunyomi: ["がけ"], onyomi: ["ガイ", "サイ", "スイ"] },
    嵯: { meanings: ["steep", "craggy", "rugged"], kunyomi: [""], onyomi: ["サ", "シ"] },
    嶋: { meanings: ["island"], kunyomi: ["しま"], onyomi: ["トウ"] },
    嶌: { meanings: ["island"], kunyomi: ["しま"], onyomi: ["トウ"] },
    嶺: { meanings: ["peak", "summit"], kunyomi: ["みね"], onyomi: ["レイ", "リョウ"] },
    嶽: { meanings: ["peak"], kunyomi: ["たけ"], onyomi: ["ガク"] },
    巌: { meanings: ["rock", "crag", "boulder"], kunyomi: ["いわ", "いわお", "けわ"], onyomi: ["ガン"] },
    已: {
      meanings: ["stop", "halt", "previously", "already", "long ago"],
      kunyomi: ["や", "すで", "のみ", "はなはだ"],
      onyomi: ["イ"],
    },
    巳: {
      meanings: ["sign of the snake or serpent", "9-11AM", "sixth sign of Chinese zodiac"],
      kunyomi: ["み"],
      onyomi: ["シ"],
    },
    巴: { meanings: ["comma-design"], kunyomi: ["ともえ", "うずまき"], onyomi: ["ハ"] },
    巷: { meanings: ["fork in road", "scene", "arena", "theater"], kunyomi: ["ちまた"], onyomi: ["コウ"] },
    巽: { meanings: ["southeast"], kunyomi: ["たつみ"], onyomi: ["ソン"] },
    帖: {
      meanings: ["quire (of paper)", "bundle of seaweed", "counter for screens", "notebook"],
      kunyomi: ["かきもの"],
      onyomi: ["チョウ", "ジョウ"],
    },
    幌: { meanings: ["canopy", "awning", "hood", "curtain"], kunyomi: ["ほろ", "とばり"], onyomi: ["コウ"] },
    幡: { meanings: ["flag"], kunyomi: ["はた"], onyomi: ["マン", "ハン", "バン", "ホン"] },
    庵: { meanings: ["hermitage", "retreat"], kunyomi: ["いおり", "いお"], onyomi: ["アン"] },
    廟: {
      meanings: ["mausoleum", "shrine", "palace"],
      kunyomi: ["たまや", "みたまや", "やしろ"],
      onyomi: ["ビョウ", "ミョウ"],
    },
    廣: {
      meanings: ["broad", "wide", "spacious"],
      kunyomi: ["ひろ", "ひろ", "ひろ", "ひろ", "ひろ"],
      onyomi: ["コウ"],
    },
    弘: { meanings: ["vast", "broad", "wide"], kunyomi: ["ひろ"], onyomi: ["コウ", "グ"] },
    弛: { meanings: ["slacken", "relax"], kunyomi: ["たる", "たる", "たゆ", "ゆる", "ゆる"], onyomi: ["チ", "シ"] },
    彗: { meanings: ["comet"], kunyomi: ["ほうき"], onyomi: ["スイ", "エ", "ケイ", "セイ"] },
    彦: { meanings: ["lad", "boy (ancient)"], kunyomi: ["ひこ"], onyomi: ["ゲン"] },
    彪: {
      meanings: ["spotted", "mottled", "patterned", "small tiger"],
      kunyomi: ["あや"],
      onyomi: ["ヒョウ", "ヒュウ"],
    },
    彬: { meanings: ["refined", "gentle"], kunyomi: ["うるわ", "あき"], onyomi: ["ヒン", "フン"] },
    彭: { meanings: ["swelling", "sound of drum"], kunyomi: [""], onyomi: ["ホウ"] },
    徘: { meanings: ["wander"], kunyomi: ["さまよ"], onyomi: ["ハイ"] },
    怜: { meanings: ["wise"], kunyomi: ["あわ", "さと"], onyomi: ["レイ", "レン", "リョウ"] },
    怨: {
      meanings: ["grudge", "show resentment", "be jealous"],
      kunyomi: ["うら", "うらみ", "うら"],
      onyomi: ["エン", "オン", "ウン"],
    },
    恣: { meanings: ["selfish", "arbitrary"], kunyomi: ["ほしいまま"], onyomi: ["シ"] },
    悌: { meanings: ["serving our elders"], kunyomi: [""], onyomi: ["テイ", "ダイ"] },
    惇: { meanings: ["sincere", "kind", "considerate"], kunyomi: ["あつ"], onyomi: ["シュン", "ジュン", "トン"] },
    惚: { meanings: ["fall in love with", "admire", "grow senile"], kunyomi: ["ほけ", "ぼ", "ほ"], onyomi: ["コツ"] },
    惟: { meanings: ["consider", "reflect", "think"], kunyomi: ["おも", "これ", "おも"], onyomi: ["イ", "ユイ"] },
    惣: { meanings: ["all"], kunyomi: ["すべ"], onyomi: ["ソウ"] },
    惧: { meanings: ["fear", "be afraid of", "dread"], kunyomi: ["おそ"], onyomi: ["ク", "グ"] },
    愁: { meanings: ["distress", "grieve", "lament", "be anxious"], kunyomi: ["うれ", "うれ"], onyomi: ["シュウ"] },
    慌: { meanings: ["disconcerted", "be confused", "lose one's head"], kunyomi: ["あわ", "あわ"], onyomi: ["コウ"] },
    慧: { meanings: ["wise"], kunyomi: ["さとい"], onyomi: ["ケイ", "エ"] },
    或: {
      meanings: ["some", "one", "or", "possibly", "a certain"],
      kunyomi: ["あ", "あるい", "あるいは"],
      onyomi: ["ワク", "コク", "イキ"],
    },
    抄: { meanings: ["extract", "selection", "summary", "copy", "spread thin"], kunyomi: [""], onyomi: ["ショウ"] },
    抒: { meanings: ["tell", "10**24"], kunyomi: ["く", "の"], onyomi: ["ジョ", "ショ"] },
    拭: { meanings: ["wipe", "mop", "swab"], kunyomi: ["ぬぐ", "ふ"], onyomi: ["ショク", "シキ"] },
    挨: { meanings: ["approach", "draw near", "push open"], kunyomi: ["ひら"], onyomi: ["アイ"] },
    挫: { meanings: ["crush", "break", "sprain", "discourage"], kunyomi: ["くじ", "くじ"], onyomi: ["ザ", "サ"] },
    挺: {
      meanings: ["counter for guns", "inksticks", "palanquins", "rickshaws", "bravely volunteer"],
      kunyomi: ["ぬ"],
      onyomi: ["チョウ", "テイ"],
    },
    捉: { meanings: ["catch", "capture"], kunyomi: ["とら"], onyomi: ["ソク", "サク"] },
    捧: {
      meanings: ["lift up", "give", "offer", "consecrate", "sacrifice", "dedicate"],
      kunyomi: ["ささ"],
      onyomi: ["ホウ"],
    },
    揃: {
      meanings: ["be complete", "uniform", "all present"],
      kunyomi: ["そろ", "そろ", "そろ", "き"],
      onyomi: ["セン"],
    },
    搜: { meanings: ["search", "seek", "investigate"], kunyomi: ["さが"], onyomi: ["ソウ", "シュ", "シュウ"] },
    摯: { meanings: ["gift", "seriousness"], kunyomi: ["いた"], onyomi: ["シ"] },
    撚: { meanings: ["twist", "twine", "kinky"], kunyomi: ["よ", "よ", "より", "ひね"], onyomi: ["ネン"] },
    撫: { meanings: ["stroke", "pat", "smooth down"], kunyomi: ["な"], onyomi: ["ブ", "フ"] },
    播: { meanings: ["plant", "sow"], kunyomi: ["ま"], onyomi: ["ハ", "バン", "ハン"] },
    敦: { meanings: ["industry", "kindliness"], kunyomi: ["あつ"], onyomi: ["トン", "タイ", "ダン", "チョウ"] },
    斑: { meanings: ["spot", "blemish", "speck", "patches"], kunyomi: ["ふ", "まだら"], onyomi: ["ハン"] },
    斥: {
      meanings: ["reject", "retreat", "recede", "withdraw", "repel", "repulse"],
      kunyomi: ["しりぞ"],
      onyomi: ["セキ"],
    },
    於: { meanings: ["at", "in", "on", "as for"], kunyomi: ["おい", "お", "ああ", "より"], onyomi: ["オ", "ヨ"] },
    旛: { meanings: ["flag"], kunyomi: ["はた"], onyomi: ["ヘン", "ハン"] },
    旭: { meanings: ["rising sun", "morning sun"], kunyomi: ["あさひ"], onyomi: ["キョク"] },
    旺: {
      meanings: ["flourishing", "successful", "beautiful", "vigorous"],
      kunyomi: ["かがや", "うつくし", "さかん"],
      onyomi: ["オウ", "キョウ", "ゴウ"],
    },
    晃: { meanings: ["clear"], kunyomi: ["あきらか"], onyomi: ["コウ"] },
    晋: { meanings: ["advance"], kunyomi: ["すす"], onyomi: ["シン"] },
    暉: { meanings: ["shine", "light"], kunyomi: ["かが"], onyomi: ["キ"] },
    暢: { meanings: ["stretch"], kunyomi: ["のび"], onyomi: ["チョウ"] },
    曼: { meanings: ["wide", "beautiful"], kunyomi: ["なが"], onyomi: ["マン", "バン"] },
    曽: {
      meanings: ["formerly", "once", "before", "ever", "never", "ex-"],
      kunyomi: ["かつ", "かつて", "すなわち"],
      onyomi: ["ソウ", "ソ", "ゾウ"],
    },
    朋: { meanings: ["companion", "friend"], kunyomi: ["とも"], onyomi: ["ホウ"] },
    朔: {
      meanings: ["conjunction (astronomy)", "first day of month", "north"],
      kunyomi: ["ついたち"],
      onyomi: ["サク"],
    },
    李: { meanings: ["plum"], kunyomi: ["すもも"], onyomi: ["リ"] },
    杖: { meanings: ["staff", "cane"], kunyomi: ["つえ"], onyomi: ["ジョウ"] },
    杜: { meanings: ["woods", "grove"], kunyomi: ["もり", "ふさ", "やまなし"], onyomi: ["ト", "トウ", "ズ"] },
    杞: { meanings: ["river willow"], kunyomi: [""], onyomi: ["コ", "キ"] },
    杭: { meanings: ["stake", "post", "picket"], kunyomi: ["くい"], onyomi: ["コウ"] },
    杵: { meanings: ["wooden pestle"], kunyomi: ["きね"], onyomi: ["ショ", "ソ"] },
    柏: { meanings: ["oak", "cypress"], kunyomi: ["かしわ"], onyomi: ["ハク", "ヒャク", "ビャク"] },
    柚: { meanings: ["citron"], kunyomi: ["ゆず"], onyomi: ["ユ", "ユウ", "ジク"] },
    柿: { meanings: ["persimmon"], kunyomi: ["かき"], onyomi: ["シ"] },
    栗: { meanings: ["chestnut"], kunyomi: ["くり", "おののく"], onyomi: ["リツ", "リ"] },
    桂: { meanings: ["Japanese Judas-tree", "cinnamon tree"], kunyomi: ["かつら"], onyomi: ["ケイ"] },
    桐: { meanings: ["paulownia"], kunyomi: ["きり"], onyomi: ["トウ", "ドウ"] },
    桝: { meanings: ["measuring box", "(kokuji)"], kunyomi: ["ます"], onyomi: [""] },
    桧: { meanings: ["Japanese cypress"], kunyomi: ["ひのき", "ひ"], onyomi: ["カイ"] },
    桶: { meanings: ["tub", "bucket"], kunyomi: ["おけ"], onyomi: ["ヨウ", "トウ"] },
    梁: {
      meanings: ["weir", "fish trap", "beam", "girder"],
      kunyomi: ["はり", "うつばり", "うちばり", "やな", "はし"],
      onyomi: ["リョウ"],
    },
    梯: { meanings: ["ladder", "stairs", "insatiable drinking"], kunyomi: ["はしご"], onyomi: ["テイ", "タイ"] },
    梶: { meanings: ["sculling oar"], kunyomi: ["かじ", "こずえ"], onyomi: ["ビ"] },
    棺: { meanings: ["coffin", "casket"], kunyomi: [""], onyomi: ["カン"] },
    椙: { meanings: ["Japanese cedar", "cryptomeria", "(kokuji)"], kunyomi: ["すぎ"], onyomi: [""] },
    椿: { meanings: ["camellia"], kunyomi: ["つばき"], onyomi: ["チン", "チュン"] },
    楊: { meanings: ["willow"], kunyomi: ["やなぎ"], onyomi: ["ヨウ"] },
    楕: { meanings: ["ellipse"], kunyomi: [""], onyomi: ["ダ", "タ"] },
    楠: { meanings: ["camphor tree"], kunyomi: ["くす", "くすのき"], onyomi: ["ナン", "ダン", "ゼン", "ネン"] },
    楢: { meanings: ["oak"], kunyomi: ["なら"], onyomi: ["シュウ", "ユウ"] },
    楼: { meanings: ["watchtower", "lookout", "high building"], kunyomi: ["たかどの"], onyomi: ["ロウ"] },
    榊: { meanings: ["sacred Shinto tree", "(kokuji)"], kunyomi: ["さかき"], onyomi: [""] },
    榎: { meanings: ["lotus tree", "nettle tree", "hackberry"], kunyomi: ["えのき"], onyomi: ["カ"] },
    榛: { meanings: ["hazelnut", "filbert"], kunyomi: ["はしばみ", "はり"], onyomi: ["シン", "ハン"] },
    槌: { meanings: ["hammer", "mallet"], kunyomi: ["つち"], onyomi: ["ツイ"] },
    槍: { meanings: ["spear", "lance", "javelin"], kunyomi: ["やり"], onyomi: ["ソウ", "ショウ"] },
    槙: { meanings: ["twig", "ornamental evergreen"], kunyomi: ["まき", "こずえ"], onyomi: ["テン", "シン"] },
    槻: { meanings: ["Zelkova tree"], kunyomi: ["つき"], onyomi: ["キ"] },
    樋: { meanings: ["water pipe", "gutter", "downspout", "conduit"], kunyomi: ["ひ", "とい"], onyomi: ["トウ"] },
    樟: { meanings: ["camphor"], kunyomi: ["くす"], onyomi: ["ショウ"] },
    樫: { meanings: ["evergreen oak", "(kokuji)"], kunyomi: ["かし"], onyomi: [""] },
    樺: { meanings: ["birch", "dark red"], kunyomi: ["かば", "かんば"], onyomi: ["カ"] },
    樽: { meanings: ["barrel", "cask", "keg"], kunyomi: ["たる"], onyomi: ["ソン"] },
    橘: { meanings: ["mandarin orange"], kunyomi: ["たちばな"], onyomi: ["キツ"] },
    橿: { meanings: ["oak"], kunyomi: ["かし", "もちのき"], onyomi: ["キョウ"] },
    檀: { meanings: ["cedar", "sandlewood", "spindle tree"], kunyomi: ["まゆみ"], onyomi: ["ダン", "タン"] },
    檄: { meanings: ["written appeal", "manifesto"], kunyomi: ["げき", "ふれぶみ"], onyomi: ["ケキ"] },
    檜: { meanings: ["Japanese cypress"], kunyomi: ["ひのき", "ひ"], onyomi: ["カイ"] },
    櫛: { meanings: ["comb"], kunyomi: ["くし", "くしけず"], onyomi: ["シツ"] },
    欣: { meanings: ["take pleasure in", "rejoice"], kunyomi: ["よろこ", "よろこ"], onyomi: ["キン", "ゴン", "コン"] },
    欽: { meanings: ["respect", "revere", "long for"], kunyomi: ["つつし"], onyomi: ["キン", "コン"] },
    此: {
      meanings: ["this", "current", "next", "coming", "last", "past"],
      kunyomi: ["これ", "この", "ここ"],
      onyomi: ["シ"],
    },
    歪: {
      meanings: ["warp", "bend", "strained", "distort"],
      kunyomi: ["いが", "いびつ", "ひず", "ゆが"],
      onyomi: ["ワイ", "エ"],
    },
    毅: { meanings: ["strong"], kunyomi: ["つよ"], onyomi: ["キ", "ギ"] },
    毬: { meanings: ["burr", "ball"], kunyomi: ["いが", "まり"], onyomi: ["キュウ"] },
    汎: { meanings: ["pan-"], kunyomi: ["ただよ", "ひろ"], onyomi: ["ハン", "ブ", "フウ", "ホウ", "ホン"] },
    汐: {
      meanings: ["eventide", "tide", "salt water", "opportunity"],
      kunyomi: ["しお", "うしお", "せい"],
      onyomi: ["セキ"],
    },
    汪: { meanings: ["flowing full", "expanse of water", "wide", "deep"], kunyomi: [""], onyomi: ["オウ"] },
    洒: { meanings: ["wash", "sprinkle"], kunyomi: ["すす", "あら"], onyomi: ["シャ", "ソン", "サイ", "セン", "セイ"] },
    洛: { meanings: ["Kyoto", "the capital"], kunyomi: [""], onyomi: ["ラク"] },
    洲: { meanings: ["continent", "sandbar", "island", "country"], kunyomi: ["しま"], onyomi: ["シュウ", "ス"] },
    洸: { meanings: ["sparkling water"], kunyomi: [""], onyomi: ["コウ"] },
    浙: { meanings: ["name of a Chinese river"], kunyomi: [""], onyomi: ["セツ"] },
    浩: { meanings: ["wide expanse", "abundance", "vigorous"], kunyomi: ["おおき", "ひろ"], onyomi: ["コウ"] },
    淘: { meanings: ["select"], kunyomi: ["よな"], onyomi: ["トウ"] },
    淳: { meanings: ["pure"], kunyomi: ["あつ"], onyomi: ["ジュン", "シュン"] },
    淵: {
      meanings: ["abyss", "edge", "deep pool", "the depths"],
      kunyomi: ["ふち", "かた", "はなわ"],
      onyomi: ["エン", "カク", "コウ"],
    },
    渕: { meanings: ["edge"], kunyomi: ["ふち", "かた", "はなわ"], onyomi: ["エン", "カク", "コウ"] },
    渚: { meanings: ["strand", "beach", "shore"], kunyomi: ["なぎさ"], onyomi: ["ショ"] },
    渥: { meanings: ["kindness", "moisten"], kunyomi: ["あつ", "うるお"], onyomi: ["アク"] },
    湊: { meanings: ["port", "harbor"], kunyomi: ["みなと", "あつ"], onyomi: ["ソウ"] },
    湘: { meanings: ["name of Chinese river", "the Sagami river"], kunyomi: [""], onyomi: ["ショウ"] },
    湛: {
      meanings: ["fill", "wear (a smile)", "clear", "pure", "dense", "deep"],
      kunyomi: ["しず", "たた"],
      onyomi: ["タン", "チン", "ジン", "セン"],
    },
    溜: {
      meanings: ["collect", "gather", "be in arrears"],
      kunyomi: ["た", "たま", "た", "したた", "たまり", "ため"],
      onyomi: ["リュウ"],
    },
    溢: { meanings: ["overflow", "inundate", "spill"], kunyomi: ["こぼ", "あふ", "み"], onyomi: ["イツ"] },
    溥: { meanings: ["far and wide"], kunyomi: ["あまねし"], onyomi: ["フ", "ハク"] },
    漕: { meanings: ["rowing", "scull", "paddle"], kunyomi: ["こ", "はこ"], onyomi: ["ソウ"] },
    漱: {
      meanings: ["gargle", "rinse mouth"],
      kunyomi: ["くちすす", "くちそそ", "うがい", "すす"],
      onyomi: ["ソウ", "シュウ", "ス"],
    },
    澤: { meanings: ["swamp"], kunyomi: ["さわ", "うるお", "うるお", "つや"], onyomi: ["タク"] },
    濡: {
      meanings: ["get wet", "damp", "make love"],
      kunyomi: ["ぬれ", "ぬら", "ぬ", "ぬ", "うるお", "うるお", "うるお"],
      onyomi: ["ジュ", "ニュ"],
    },
    瀋: { meanings: ["juice", "broth"], kunyomi: [""], onyomi: ["シン"] },
    瀕: { meanings: ["shore", "brink", "verge"], kunyomi: ["ほとり"], onyomi: ["ヒン"] },
    灘: { meanings: ["open sea"], kunyomi: ["なだ", "せ"], onyomi: ["タン", "ダン"] },
    炒: { meanings: ["broil", "parch", "roast", "fry"], kunyomi: ["い", "いた"], onyomi: ["ソウ", "ショウ"] },
    焉: { meanings: ["how", "why", "then"], kunyomi: ["いずく", "ここに", "これ"], onyomi: ["エン"] },
    煎: { meanings: ["broil", "parch", "roast", "boil"], kunyomi: ["せん", "い", "に"], onyomi: ["セン"] },
    煕: {
      meanings: ["shine"],
      kunyomi: ["たのし", "ひか", "ひろ", "よろこ", "かわ", "あきらか", "ひろ", "ひろ"],
      onyomi: ["キ"],
    },
    煥: { meanings: ["shine"], kunyomi: ["あきらか"], onyomi: ["カン"] },
    燈: {
      meanings: ["lamp", "light", "counter for lights"],
      kunyomi: ["ひ", "ほ-", "ともしび", "とも", "あかり"],
      onyomi: ["トウ"],
    },
    燕: { meanings: ["swallow (bird)"], kunyomi: ["つばめ", "つばくら", "つばくろ"], onyomi: ["エン"] },
    牌: { meanings: ["label", "signboard", "medal", "mahjong tiles"], kunyomi: ["ぱい", "ふだ"], onyomi: ["ハイ"] },
    牝: { meanings: ["female"], kunyomi: ["めす", "め-", "めん"], onyomi: ["ヒン"] },
    牟: { meanings: ["pupil (eye)", "moo (cow sound)"], kunyomi: [""], onyomi: ["ボウ", "ム"] },
    牡: { meanings: ["male"], kunyomi: ["おす", "お-", "おん-"], onyomi: ["ボ", "ボウ"] },
    牢: { meanings: ["prison", "jail", "hardness"], kunyomi: ["かた", "ひとや"], onyomi: ["ロウ"] },
    犀: { meanings: ["rhinocerous"], kunyomi: [""], onyomi: ["サイ", "セイ"] },
    狛: { meanings: ["archaic part of Korea", "lion-dog shrine guards"], kunyomi: ["こま"], onyomi: ["ハク"] },
    狸: { meanings: ["tanuki", "raccoon"], kunyomi: ["たぬき"], onyomi: ["リ", "ライ"] },
    狼: { meanings: ["wolf"], kunyomi: ["おおかみ"], onyomi: ["ロウ"] },
    猪: { meanings: ["boar"], kunyomi: ["い", "いのしし"], onyomi: ["チョ"] },
    猷: { meanings: ["plan", "scheme", "plot", "way"], kunyomi: ["はかりごと", "はか"], onyomi: ["ユウ", "ヨウ"] },
    獅: { meanings: ["lion"], kunyomi: ["しし"], onyomi: ["シ"] },
    玩: {
      meanings: ["play", "take pleasure in", "trifle with", "make sport of"],
      kunyomi: ["もちあそ", "もてあそ"],
      onyomi: ["ガン"],
    },
    玲: { meanings: ["sound of jewels"], kunyomi: [""], onyomi: ["レイ"] },
    珂: { meanings: ["jewel"], kunyomi: [""], onyomi: ["カ"] },
    琉: { meanings: ["precious stone", "gem", "lapis lazuli"], kunyomi: [""], onyomi: ["リュウ", "ル"] },
    琢: { meanings: ["polish"], kunyomi: ["みが"], onyomi: ["タク"] },
    琵: { meanings: ["glissando on strings", "lute"], kunyomi: [""], onyomi: ["ビ", "ヒ"] },
    琶: { meanings: ["lute"], kunyomi: [""], onyomi: ["ハ", "ベ", "ワ"] },
    瓦: { meanings: ["tile", "gram"], kunyomi: ["かわら", "ぐらむ"], onyomi: ["ガ"] },
    甕: { meanings: ["jar", "jug", "vat"], kunyomi: ["かめ", "みか"], onyomi: ["オウ"] },
    甦: { meanings: ["be resuscitated", "revived"], kunyomi: ["よみがえ"], onyomi: ["ソ", "コウ"] },
    甫: { meanings: ["for the first time", "not until"], kunyomi: ["はじ"], onyomi: ["ホ", "フ"] },
    畏: {
      meanings: ["fear", "majestic", "graciously", "be apprehensive"],
      kunyomi: ["おそ", "かしこま", "かしこ", "かしこ"],
      onyomi: ["イ"],
    },
    畝: {
      meanings: ["furrow", "thirty tsubo", "ridge", "rib"],
      kunyomi: ["せ", "うね"],
      onyomi: ["ボウ", "ホ", "モ", "ム"],
    },
    畠: { meanings: ["field", "farm", "garden", "(kokuji)"], kunyomi: ["はたけ", "はた"], onyomi: [""] },
    畿: { meanings: ["capital", "suburbs of capital"], kunyomi: ["みやこ"], onyomi: ["キ"] },
    痕: { meanings: ["mark", "foot print"], kunyomi: ["あと"], onyomi: ["コン"] },
    瘤: { meanings: ["lump", "swelling"], kunyomi: ["こぶ"], onyomi: ["リュウ", "ル"] },
    癌: { meanings: ["cancer", "cancerous evil"], kunyomi: [""], onyomi: ["ガン"] },
    皐: { meanings: ["swamp", "shore"], kunyomi: ["さつき"], onyomi: ["コウ"] },
    皓: { meanings: ["white", "clear"], kunyomi: ["しろ", "ひか"], onyomi: ["コウ"] },
    盧: { meanings: ["hut"], kunyomi: [""], onyomi: ["ロ"] },
    眉: { meanings: ["eyebrow"], kunyomi: ["まゆ"], onyomi: ["ビ", "ミ"] },
    眞: { meanings: ["truth", "reality", "Buddhist sect"], kunyomi: ["ま", "まこと"], onyomi: ["シン"] },
    瞑: {
      meanings: ["sleep", "dark", "close eyes"],
      kunyomi: ["めい", "つぶ", "つむ", "くら"],
      onyomi: ["メイ", "ベン", "ミョウ", "ミン", "メン"],
    },
    矩: { meanings: ["ruler", "carpenter's square"], kunyomi: ["かね", "かねざし", "さしがね"], onyomi: ["ク"] },
    砦: { meanings: ["fort", "stronghold", "entrenchments"], kunyomi: ["とりで"], onyomi: ["サイ"] },
    硝: { meanings: ["nitrate", "saltpeter"], kunyomi: [""], onyomi: ["ショウ"] },
    硯: { meanings: ["inkstone"], kunyomi: ["すずり"], onyomi: ["ケン", "ゲン"] },
    碓: { meanings: ["pestle"], kunyomi: ["たし", "かく"], onyomi: ["カク", "タイ"] },
    碧: { meanings: ["blue", "green"], kunyomi: [""], onyomi: ["ヘキ", "ヒャク"] },
    磐: { meanings: ["rock", "crag", "cliff", "wall (in a mine)"], kunyomi: ["いわ"], onyomi: ["バン", "ハン"] },
    磯: { meanings: ["seashore", "beach"], kunyomi: ["いそ"], onyomi: ["キ"] },
    礒: { meanings: ["rock", "beach", "shore"], kunyomi: ["いそ", "いわお"], onyomi: ["ギ", "ガ"] },
    祇: {
      meanings: ["national or local god", "peaceful", "great"],
      kunyomi: ["くにつかみ", "ただ", "まさに"],
      onyomi: ["ギ", "キ", "シ"],
    },
    祐: { meanings: ["help"], kunyomi: ["たす"], onyomi: ["ユウ", "ウ"] },
    禄: {
      meanings: ["fief", "allowance", "pension", "grant", "happiness"],
      kunyomi: ["さいわ", "ふち"],
      onyomi: ["ロク"],
    },
    禎: { meanings: ["happiness", "blessed", "good fortune", "auspicious"], kunyomi: ["さいわ"], onyomi: ["テイ"] },
    秦: { meanings: ["Manchu dynasty", "name given to naturalized foreigners"], kunyomi: ["はた"], onyomi: ["シン"] },
    稀: { meanings: ["rare", "phenomenal", "dilute (acid)"], kunyomi: ["まれ", "まばら"], onyomi: ["キ", "ケ"] },
    稔: { meanings: ["harvest", "ripen"], kunyomi: ["みの", "みのり"], onyomi: ["ネン", "ジン", "ニン"] },
    稜: {
      meanings: ["angle", "edge", "corner", "power", "majesty"],
      kunyomi: ["いつ", "かど"],
      onyomi: ["リョウ", "ロウ"],
    },
    稽: { meanings: ["think", "consider"], kunyomi: ["かんが", "とど"], onyomi: ["ケイ"] },
    穣: { meanings: ["good crops", "prosperity", "10**28"], kunyomi: ["わら", "ゆたか"], onyomi: ["ジョウ"] },
    窪: {
      meanings: ["depression", "cave in", "sink", "become hollow"],
      kunyomi: ["くぼ", "くぼ", "くぼ", "くぼ"],
      onyomi: ["ワ", "ア"],
    },
    窯: { meanings: ["kiln", "oven", "furnace"], kunyomi: ["かま"], onyomi: ["ヨウ"] },
    竪: { meanings: ["length", "height", "warp"], kunyomi: ["たて", "た", "こども"], onyomi: ["ジュ"] },
    竿: { meanings: ["pole", "rod", "scale beam", "violin neck"], kunyomi: ["さお"], onyomi: ["カン"] },
    笏: { meanings: ["mace", "baton", "scepter"], kunyomi: ["しゃく"], onyomi: ["コツ"] },
    笘: { meanings: ["whip", "cane", "wooden writing slate"], kunyomi: [""], onyomi: ["セン", "チョウ"] },
    笹: { meanings: ["bamboo grass", "(kokuji)"], kunyomi: ["ささ"], onyomi: [""] },
    筑: { meanings: ["an ancient musical instrument"], kunyomi: [""], onyomi: ["チク"] },
    箏: { meanings: ["a koto"], kunyomi: ["こと"], onyomi: ["ソウ", "ショウ"] },
    箕: { meanings: ["winnowing"], kunyomi: ["み"], onyomi: ["キ"] },
    篆: { meanings: ["seal-style characters"], kunyomi: [""], onyomi: ["テン"] },
    篇: { meanings: ["volume", "chapter", "book", "editing", "compilation"], kunyomi: [""], onyomi: ["ヘン"] },
    篠: { meanings: ["bamboo grass"], kunyomi: ["しの", "ささ", "すず"], onyomi: ["ゾウ", "ショウ"] },
    篭: {
      meanings: ["seclude oneself", "cage", "coop", "implied"],
      kunyomi: ["かご", "こ", "こも", "こ"],
      onyomi: ["ロウ", "ル"],
    },
    簑: { meanings: ["a coat raincoat"], kunyomi: ["みの"], onyomi: ["サ", "サイ"] },
    簗: { meanings: ["weir", "fish trap", "(kokuji)"], kunyomi: ["やな"], onyomi: ["リョウ"] },
    粕: { meanings: ["scrap", "waste"], kunyomi: ["かす"], onyomi: ["ハク"] },
    粟: { meanings: ["millet"], kunyomi: ["あわ", "もみ"], onyomi: ["ゾク", "ショク", "ソク"] },
    粥: { meanings: ["rice gruel"], kunyomi: ["かゆ", "かい", "ひさ"], onyomi: ["イク", "シュク", "ジュク"] },
    糞: { meanings: ["shit", "feces", "excrement"], kunyomi: ["くそ"], onyomi: ["フン"] },
    紘: { meanings: ["large"], kunyomi: ["おおづな", "つな", "つなぐ"], onyomi: ["コウ"] },
    絆: { meanings: ["bonds", "fetters"], kunyomi: ["きずな", "ほだ", "つな"], onyomi: ["ハン"] },
    絢: { meanings: ["brilliant fabric design"], kunyomi: [""], onyomi: ["ケン"] },
    綜: { meanings: ["rule", "synthesize"], kunyomi: ["おさ", "す"], onyomi: ["ソウ"] },
    綴: {
      meanings: ["compose", "spell", "write", "bind (books)"],
      kunyomi: ["と", "つづ", "つづり", "すみ"],
      onyomi: ["テイ", "テツ", "テチ", "ゲツ"],
    },
    緻: { meanings: ["fine (i.e. not coarse)"], kunyomi: ["こまか"], onyomi: ["チ"] },
    縞: { meanings: ["stripe"], kunyomi: ["しま", "しろぎぬ"], onyomi: ["コウ"] },
    繕: { meanings: ["darning", "repair", "mend", "trim", "tidy up", "adjust"], kunyomi: ["つくろ"], onyomi: ["ゼン"] },
    繭: { meanings: ["cocoon"], kunyomi: ["まゆ", "きぬ"], onyomi: ["ケン"] },
    罵: { meanings: ["abuse", "insult"], kunyomi: ["ののし"], onyomi: ["バ"] },
    翁: { meanings: ["venerable old man"], kunyomi: ["おきな"], onyomi: ["オウ"] },
    翠: { meanings: ["green", "kingfisher"], kunyomi: ["かわせみ", "みどり"], onyomi: ["スイ"] },
    翫: { meanings: ["take pleasure in", "play instrument"], kunyomi: ["もてあそ"], onyomi: ["ガン"] },
    耀: { meanings: ["shine", "sparkle", "gleam", "twinkle"], kunyomi: ["かがや", "ひかり"], onyomi: ["ヨウ"] },
    聯: { meanings: ["party", "gang", "clique"], kunyomi: ["つら", "つら"], onyomi: ["レン"] },
    肇: { meanings: ["beginning"], kunyomi: ["はじ", "はじめ"], onyomi: ["チョウ", "ジョウ", "トウ"] },
    股: { meanings: ["thigh", "crotch"], kunyomi: ["また", "もも"], onyomi: ["コ"] },
    肢: { meanings: ["limb", "arms & legs"], kunyomi: [""], onyomi: ["シ"] },
    胚: { meanings: ["embryo"], kunyomi: ["はらみ", "はら"], onyomi: ["ハイ"] },
    脩: { meanings: ["dried meat"], kunyomi: ["おさ", "なが", "ほじし"], onyomi: ["シュウ"] },
    腎: { meanings: ["kidney"], kunyomi: [""], onyomi: ["ジン"] },
    腫: { meanings: ["tumor", "swelling"], kunyomi: ["は", "は", "は", "く", "はれもの"], onyomi: ["シュ", "ショウ"] },
    膝: { meanings: ["knee", "lap"], kunyomi: ["ひざ"], onyomi: ["シツ"] },
    膠: { meanings: ["glue", "isinglass"], kunyomi: ["にかわ", "にべ"], onyomi: ["コウ", "キョウ"] },
    膳: { meanings: ["small low table", "tray"], kunyomi: ["かしわ", "すす", "そな"], onyomi: ["ゼン", "セン"] },
    臼: { meanings: ["mortar"], kunyomi: ["うす", "うすづ"], onyomi: ["キュウ", "グ"] },
    舘: { meanings: ["mansion", "large building", "palace"], kunyomi: ["やかた", "たて"], onyomi: ["カン"] },
    舛: { meanings: ["dancing radical (no. 136)"], kunyomi: ["まい", "そむ"], onyomi: ["ブ", "セン"] },
    舜: { meanings: ["type of morning glory", "rose of Sharon", "althea"], kunyomi: [""], onyomi: ["シュン"] },
    舩: { meanings: ["boat", "ship", "vessel"], kunyomi: ["ふね", "ふな-"], onyomi: ["セン"] },
    舵: { meanings: ["rudder", "helm", "wheel"], kunyomi: ["かじ"], onyomi: ["ダ", "タ"] },
    艶: {
      meanings: ["glossy", "luster", "glaze", "polish", "charm", "colorful", "captivating"],
      kunyomi: ["つや", "なま", "あで", "つや", "なま"],
      onyomi: ["エン"],
    },
    芙: { meanings: ["lotus", "Mt Fuji"], kunyomi: [""], onyomi: ["フ"] },
    芥: {
      meanings: ["mustard", "rape", "dust", "trash", "rubbish"],
      kunyomi: ["からし", "ごみ", "あくた"],
      onyomi: ["カイ", "ケ"],
    },
    芦: { meanings: ["reed", "bullrush"], kunyomi: ["あし", "よし"], onyomi: ["ロ"] },
    芭: { meanings: ["banana"], kunyomi: [""], onyomi: ["バ", "ハ"] },
    芹: { meanings: ["parsley"], kunyomi: ["せり"], onyomi: ["キン"] },
    苅: { meanings: ["cutting (grass)"], kunyomi: ["か"], onyomi: ["ガイ", "カイ"] },
    苑: { meanings: ["garden", "farm", "park"], kunyomi: ["その", "う"], onyomi: ["エン", "オン"] },
    苫: { meanings: ["rush matting"], kunyomi: ["とま"], onyomi: ["セン"] },
    茅: { meanings: ["miscanthus reed"], kunyomi: ["かや", "ちがや"], onyomi: ["ボウ", "ミョウ"] },
    茗: { meanings: ["tea"], kunyomi: ["ちゃ"], onyomi: ["ミョウ", "メイ"] },
    荏: { meanings: ["bean", "perilla", "herb", "soft", "pliable"], kunyomi: [""], onyomi: ["ジン", "ニン"] },
    荻: { meanings: ["reed", "rush"], kunyomi: ["おぎ"], onyomi: ["テキ"] },
    菩: { meanings: ["kind of grass", "sacred tree"], kunyomi: [""], onyomi: ["ボ"] },
    菱: { meanings: ["diamond (shape)", "water chestnut", "rhombus"], kunyomi: ["ひし"], onyomi: ["リョウ"] },
    萩: { meanings: ["bush clover"], kunyomi: ["はぎ"], onyomi: ["シュウ"] },
    萬: { meanings: ["ten thousand", "10", "000"], kunyomi: ["よろず"], onyomi: ["マン", "バン"] },
    萱: { meanings: ["miscanthus reed"], kunyomi: ["かや", "かんぞう"], onyomi: ["ケン"] },
    葛: { meanings: ["arrowroot", "kudzu"], kunyomi: ["つづら", "くず"], onyomi: ["カツ", "カチ"] },
    葦: { meanings: ["reed", "bullrush"], kunyomi: ["しお", "しな", "しぼ", "な"], onyomi: ["イ"] },
    蒋: { meanings: ["reed"], kunyomi: ["まこも", "はげ"], onyomi: ["ショウ", "ソウ"] },
    蒔: { meanings: ["sow (seeds)"], kunyomi: ["う", "ま"], onyomi: ["シ", "ジ"] },
    蒲: {
      meanings: ["bullrush", "flag", "cattail"],
      kunyomi: ["がま", "かば", "かま"],
      onyomi: ["ホ", "ボ", "フ", "ブ"],
    },
    蓋: {
      meanings: ["cover", "lid", "flap"],
      kunyomi: ["ふた", "けだ", "おお", "かさ", "かこう"],
      onyomi: ["ガイ", "カイ", "コウ"],
    },
    蓼: { meanings: ["luxurious grass", "a smartweed"], kunyomi: ["たで"], onyomi: ["シン", "リク", "リョウ"] },
    蔡: { meanings: ["type of tortoise used for divination"], kunyomi: [""], onyomi: ["サイ"] },
    蔦: { meanings: ["vine", "ivy"], kunyomi: ["つた"], onyomi: ["チョウ"] },
    蔭: { meanings: ["shade", "shadow", "backing assistance"], kunyomi: ["かげ"], onyomi: ["イン", "オン"] },
    蕃: { meanings: ["grow luxuriously"], kunyomi: [""], onyomi: ["バン", "ハン"] },
    蕉: { meanings: ["banana", "plantain"], kunyomi: [""], onyomi: ["ショウ"] },
    蕨: { meanings: ["bracken", "fernbrake"], kunyomi: ["わらび"], onyomi: ["ケツ"] },
    薔: { meanings: ["water pepper"], kunyomi: ["みずたで"], onyomi: ["バ", "ショウ", "ショク", "ソウ"] },
    薩: { meanings: ["salvation", "Buddha"], kunyomi: [""], onyomi: ["サツ", "サチ"] },
    薪: { meanings: ["fuel", "firewood", "kindling"], kunyomi: ["たきぎ", "まき"], onyomi: ["シン"] },
    薫: {
      meanings: ["send forth fragrance", "fragrant", "be scented", "smoke (tobacco)"],
      kunyomi: ["かお"],
      onyomi: ["クン"],
    },
    薮: { meanings: ["thicket", "bush", "underbrush", "grove"], kunyomi: ["やぶ"], onyomi: ["ソウ"] },
    藁: { meanings: ["straw"], kunyomi: ["わら"], onyomi: ["コウ"] },
    藏: { meanings: ["hide", "own", "have", "possess"], kunyomi: ["くら", "おさ", "かく"], onyomi: ["ゾウ", "ソウ"] },
    藝: {
      meanings: ["art", "craft", "performance", "acting", "trick", "stunt"],
      kunyomi: ["う", "のり", "わざ"],
      onyomi: ["ゲイ", "ウン"],
    },
    蘇: { meanings: ["be resuscitated", "revived", "perilla", "shiso"], kunyomi: ["よみがえ"], onyomi: ["ソ", "ス"] },
    蘭: { meanings: ["orchid", "Holland"], kunyomi: [""], onyomi: ["ラン", "ラ"] },
    蚕: { meanings: ["silkworm"], kunyomi: ["かいこ", "こ"], onyomi: ["サン", "テン"] },
    蛋: { meanings: ["barbarian", "egg"], kunyomi: [""], onyomi: ["タン"] },
    蛭: { meanings: ["leech"], kunyomi: ["ひる"], onyomi: ["シツ", "チツ"] },
    蜷: { meanings: ["an edible river snail"], kunyomi: ["にな"], onyomi: ["ケン"] },
    衷: { meanings: ["inmost", "heart", "mind", "inside"], kunyomi: [""], onyomi: ["チュウ"] },
    袁: { meanings: ["long kimono"], kunyomi: [""], onyomi: ["エン", "オン"] },
    袖: {
      meanings: ["sleeve", "wing (building)", "extension", "give cold shoulder"],
      kunyomi: ["そで"],
      onyomi: ["シュウ"],
    },
    袴: { meanings: ["men's formal divided skirt"], kunyomi: ["はかま", "ずぼん"], onyomi: ["コ", "ク"] },
    裾: { meanings: ["cuff", "hem", "foot of mountain"], kunyomi: ["すそ"], onyomi: ["キョ", "コ"] },
    褐: { meanings: ["brown", "woollen kimono"], kunyomi: [""], onyomi: ["カツ"] },
    襄: { meanings: ["rise", "raise"], kunyomi: ["はら"], onyomi: ["ジョウ", "ショウ"] },
    訃: { meanings: ["obituary"], kunyomi: ["しらせ"], onyomi: ["フ"] },
    詔: { meanings: ["imperial edict"], kunyomi: ["みことのり"], onyomi: ["ショウ"] },
    詫: { meanings: ["apologize"], kunyomi: ["わび", "わび", "かこつ", "わ", "わび"], onyomi: ["タ"] },
    諌: { meanings: ["admonish", "dissuade"], kunyomi: ["いさ", "いさ"], onyomi: ["カン"] },
    諏: { meanings: ["consult"], kunyomi: ["そう", "はか"], onyomi: ["シュ", "ス"] },
    諜: { meanings: ["spy out", "reconnoiter"], kunyomi: ["ちょう", "うかが", "しめ"], onyomi: ["チョウ"] },
    諦: {
      meanings: ["truth", "clarity", "abandon", "give up"],
      kunyomi: ["あきら", "つまびらか", "まこと"],
      onyomi: ["テイ", "タイ"],
    },
    謄: { meanings: ["mimeograph", "copy"], kunyomi: [""], onyomi: ["トウ"] },
    謳: { meanings: ["extol", "declare", "express"], kunyomi: ["うた"], onyomi: ["オウ", "ウ"] },
    讃: { meanings: ["praise", "title on a picture"], kunyomi: ["ほ", "たた"], onyomi: ["サン"] },
    貰: { meanings: ["get", "have", "obtain"], kunyomi: ["もら"], onyomi: ["セイ", "シャ"] },
    賜: { meanings: ["grant", "gift", "boon", "results"], kunyomi: ["たまわ", "たま", "たも"], onyomi: ["シ"] },
    贋: { meanings: ["counterfeit", "forgery"], kunyomi: ["にせ"], onyomi: ["ガン"] },
    赳: { meanings: ["strong and brave"], kunyomi: [""], onyomi: ["キュウ"] },
    趙: { meanings: ["nimble", "late-going"], kunyomi: [""], onyomi: ["チョウ", "ジョウ", "キョウ"] },
    蹄: { meanings: ["hoof"], kunyomi: ["ひづめ"], onyomi: ["テイ"] },
    蹴: { meanings: ["kick"], kunyomi: ["け"], onyomi: ["シュク", "シュウ"] },
    轍: { meanings: ["rut", "wheel track"], kunyomi: ["わだちい", "わだち"], onyomi: ["テツ"] },
    轟: { meanings: ["roar", "thunder", "boom resound"], kunyomi: ["とどろ", "とどろ"], onyomi: ["ゴウ", "コウ"] },
    辰: {
      meanings: ["sign of the dragon", "7-9AM", "fifth sign of Chinese zodiac", "shin dragon radical (no. 161)"],
      kunyomi: ["たつ"],
      onyomi: ["シン", "ジン"],
    },
    辻: { meanings: ["crossing", "crossroad", "street corners", "(kokuji)"], kunyomi: ["つじ"], onyomi: [""] },
    迦: { meanings: ["(used phonetically)"], kunyomi: [""], onyomi: ["カ", "ケ"] },
    逐: {
      meanings: ["pursue", "drive away", "chase", "accomplish", "attain", "commit"],
      kunyomi: [""],
      onyomi: ["チク"],
    },
    逓: { meanings: ["relay", "in turn", "sending"], kunyomi: ["かわ", "たがいに"], onyomi: ["テイ"] },
    逗: { meanings: ["stop"], kunyomi: ["とど"], onyomi: ["トウ", "ズ"] },
    逢: { meanings: ["meeting", "tryst", "date", "rendezvous"], kunyomi: ["あ", "むか"], onyomi: ["ホウ"] },
    邑: {
      meanings: ["village", "rural community", "right village radical (no. 163)"],
      kunyomi: ["むら"],
      onyomi: ["ユウ"],
    },
    郁: { meanings: ["cultural progress", "perfume"], kunyomi: [""], onyomi: ["イク"] },
    鄒: { meanings: ["place name"], kunyomi: [""], onyomi: ["スウ", "シュ", "シュウ"] },
    鄭: { meanings: ["an ancient Chinese province"], kunyomi: [""], onyomi: ["テイ", "ジョウ"] },
    酉: {
      meanings: ["west", "bird", "sign of the bird", "5-7PM", "tenth sign of Chinese zodiac", "sake radical (no. 164)"],
      kunyomi: ["とり"],
      onyomi: ["ユウ"],
    },
    醍: { meanings: ["whey", "good Buddhist teaching"], kunyomi: [""], onyomi: ["ダイ", "タイ", "テイ"] },
    釘: { meanings: ["nail", "tack", "peg"], kunyomi: ["くぎ"], onyomi: ["テイ", "チョウ"] },
    釜: { meanings: ["kettle", "cauldron", "iron pot"], kunyomi: ["かま"], onyomi: ["フ"] },
    釧: { meanings: ["bracelet"], kunyomi: ["くしろ", "うでわ"], onyomi: ["セン"] },
    鉾: { meanings: ["halberd", "arms", "festival float"], kunyomi: ["ほこ"], onyomi: ["ボウ", "ム"] },
    銕: { meanings: ["iron", "strong", "solid", "firm"], kunyomi: ["くろがね"], onyomi: ["テツ"] },
    銚: { meanings: ["sake bottle"], kunyomi: ["なべ"], onyomi: ["チョウ", "ヨウ"] },
    錫: { meanings: ["copper", "tin"], kunyomi: ["すず", "たま"], onyomi: ["セキ", "シャク"] },
    鍼: { meanings: ["needle"], kunyomi: ["はり", "さ"], onyomi: ["シン"] },
    鍾: {
      meanings: ["spindle", "gather", "collect"],
      kunyomi: ["あつ", "さかずき", "かね"],
      onyomi: ["ショウ", "シュ"],
    },
    闊: { meanings: ["wide"], kunyomi: ["ひろ"], onyomi: ["カツ"] },
    附: { meanings: ["affixed", "attach", "refer to", "append"], kunyomi: ["つ", "つ"], onyomi: ["フ"] },
    隈: { meanings: ["corner", "nook", "recess"], kunyomi: ["くま", "すみ"], onyomi: ["ワイ", "エ"] },
    雀: { meanings: ["sparrow"], kunyomi: ["すずめ"], onyomi: ["ジャク", "ジャン", "サク", "シャク"] },
    雁: { meanings: ["wild goose"], kunyomi: ["かり", "かりがね"], onyomi: ["ガン"] },
    雛: {
      meanings: ["chick", "squab", "duckling", "doll"],
      kunyomi: ["ひな", "ひよこ"],
      onyomi: ["スウ", "ス", "ジュ"],
    },
    雫: { meanings: ["drop", "trickle", "dripping", "(kokuji)"], kunyomi: ["しずく"], onyomi: ["ダ"] },
    霞: { meanings: ["be hazy", "grow dim", "blurred"], kunyomi: ["かすみ", "かす"], onyomi: ["カ", "ゲ"] },
    鞍: { meanings: ["saddle"], kunyomi: ["くら"], onyomi: ["アン"] },
    韮: { meanings: ["leek"], kunyomi: ["にら"], onyomi: ["キュウ", "ク"] },
    韻: { meanings: ["rhyme", "elegance", "tone"], kunyomi: [""], onyomi: ["イン"] },
    頒: { meanings: ["distribute", "disseminate", "partition", "understand"], kunyomi: ["わか"], onyomi: ["ハン"] },
    頚: { meanings: ["neck", "head"], kunyomi: ["くび"], onyomi: ["ケイ"] },
    頬: { meanings: ["cheeks", "jaw"], kunyomi: ["ほお", "ほほ"], onyomi: ["キョウ"] },
    餅: { meanings: ["mochi rice cake"], kunyomi: ["もち", "もちい"], onyomi: ["ヘイ", "ヒョウ"] },
    餌: {
      meanings: ["food", "bait", "prey", "tempting profit"],
      kunyomi: ["え", "えば", "えさ", "もち"],
      onyomi: ["ジ", "ニ"],
    },
    饗: { meanings: ["banquet"], kunyomi: ["う", "もてな"], onyomi: ["キョウ"] },
    馨: { meanings: ["fragrant", "balmy", "favourable"], kunyomi: ["かお", "かおり"], onyomi: ["ケイ", "キョウ"] },
    魁: { meanings: ["charging ahead of others"], kunyomi: ["さきがけ", "かしら"], onyomi: ["カイ"] },
    魏: { meanings: ["high", "large", "Kingdom of Wei"], kunyomi: ["たか"], onyomi: ["ギ"] },
    魯: { meanings: ["foolish", "Russia"], kunyomi: ["おろか"], onyomi: ["ロ"] },
    鮎: { meanings: ["freshwater trout", "smelt"], kunyomi: ["あゆ", "なまず"], onyomi: ["デン", "ネン"] },
    鮫: { meanings: ["shark"], kunyomi: ["さめ", "みずち"], onyomi: ["コウ"] },
    鮭: { meanings: ["salmon"], kunyomi: ["さけ", "しゃけ", "ふぐ"], onyomi: ["カイ", "ケイ"] },
    鯛: { meanings: ["sea bream", "red snapper"], kunyomi: ["たい"], onyomi: ["チョウ"] },
    鱒: { meanings: ["salmon trout"], kunyomi: ["ます"], onyomi: ["ソン", "セン", "ザン"] },
    鱗: { meanings: ["scales (fish)"], kunyomi: ["うろこ", "こけ", "こけら"], onyomi: ["リン"] },
    鳳: { meanings: ["male mythical bird"], kunyomi: [""], onyomi: ["ホウ", "フウ"] },
    鴈: { meanings: ["wild goose"], kunyomi: ["かり", "かりがね"], onyomi: ["ガン"] },
    鴎: { meanings: ["seagull"], kunyomi: ["かもめ"], onyomi: ["オウ"] },
    鴨: { meanings: ["wild duck", "easy mark"], kunyomi: ["かも", "あひる"], onyomi: ["オウ"] },
    鴻: {
      meanings: ["large bird", "wild goose", "large", "great", "powerful", "prosperous"],
      kunyomi: ["おおとり", "ひしくい", "おおがり"],
      onyomi: ["コウ", "ゴウ"],
    },
    鵜: { meanings: ["cormorant"], kunyomi: ["う"], onyomi: ["テイ", "ダイ"] },
    鵠: { meanings: ["swan"], kunyomi: ["くぐい", "まと"], onyomi: ["コク", "コウ"] },
    鵬: { meanings: ["phoenix"], kunyomi: ["おおとり"], onyomi: ["ホウ"] },
    鷲: { meanings: ["eagle"], kunyomi: ["わし"], onyomi: ["シュウ", "ジュ"] },
    鷹: { meanings: ["hawk"], kunyomi: ["たか"], onyomi: ["ヨウ", "オウ"] },
    鷺: { meanings: ["heron"], kunyomi: ["さぎ"], onyomi: ["ロ"] },
    麓: { meanings: ["foot of a mountain"], kunyomi: ["ふもと"], onyomi: ["ロク"] },
    麹: { meanings: ["malt", "yeast"], kunyomi: ["こうじ"], onyomi: ["キク"] },
    麺: { meanings: ["noodles", "wheat flour"], kunyomi: ["むぎこ"], onyomi: ["メン", "ベン"] },
    黎: { meanings: ["dark", "black", "many"], kunyomi: ["くろ"], onyomi: ["レイ", "リ"] },
    黛: { meanings: ["blackened eyebrows"], kunyomi: ["まゆずみ"], onyomi: ["タイ"] },
  };

  wkof.set_state("wkof.freq.kanji", "ready");
})(window);
