// ==UserScript==
// @version     1.0.0
// @copyright   2018+, Robin Findley
// ==/UserScript==

// Console code to fetch details:
//var klist = '丑丙丞亘亥亦亨伍伶伽但佑侃侑侯倖倣倭偲儒允冴冶凜凪凱勁勅勺匁匡卯厘叡只叶吏啄喬嗣嚇圭塑墾壱奎嫡嬉孟宏宥宵寅尭峻崚嵩嵯嶺巌巳巴巽弐弘彗彦彪彬怜恕悌惇惟惣愁慧抄捷捺敦斤斥於旭旺昂昴晃晋晏晟晨暉暢朋朔朕李杜柊柚柾栗桂桐梢梧棺椋椰椿楊楠楼榛槙槻樺橘檀欣欽毅毬汐洲洵洸浩淳渚渥滉漱澪濫熙燎燦燿爵爾猪玖玲琉琢琳瑚瑳瑶甫畝痘皐皓眉眸硝碧碩磯祐禄禎秦稀稔稜穣窯竣笙笹箇紗紘紬絃絢綜綸繕繭翁翠耀耗耶肇肢胤脩脹舜艶芙芹苑茄茅茉莞菖菫萩蒔蓉蔦蕉蕗薪薫蘭虞蚕衷衿袈裟褐詔詢誼諄謁謄賜賦赳辰迪逐逓遵邑郁酉采銑錘附雛霞鞠韻頌頒馨魁鮎鯛鳳鴻鵬鷹麟麿黎黛';
//function toarr(s) {return s.replace(/(^\s+|\s+$)/g,'').replace(/'/g,'\\\'').replace(/\s*[,、]\s*/g,',').split(',');}
//function clean_yomi(s) {return s.replace(/\..*/g,'');}
//Promise.all(klist.split('').map(kanji => {
//    return $.get('https://jisho.org/search/%23kanji%20'+kanji).then(content => {
//        let html = $(content);
//        let meanings = toarr(html.find('.kanji-details__main-meanings').text());
//        let onyomi = toarr(html.find('.on_yomi .kanji-details__main-readings-list').text()).map(clean_yomi);
//        let kunyomi = toarr(html.find('.kun_yomi .kanji-details__main-readings-list').text()).map(clean_yomi);
//        return '        \''+kanji+'\': {'+
//            'meanings:[\''+meanings.join('\',\'')+'\'], '+
//            'kunyomi:[\''+kunyomi.join('\',\'')+'\'], '+
//            'onyomi:[\''+onyomi.join('\',\'')+'\']},';
//    });
//})).then(results => {
//    results.sort((a,b) => a[9].localeCompare(b[9]));
//    console.log(results.join('\n'));
//});

(function(gobj) {

    if (!gobj.jlpt) gobj.jlpt = {};

    let jlpt = gobj.jlpt;

    jlpt.kanji_by_level = [
    	{name:'N5', kanji:'日一国人年大十二本中長出三時行見月後前生五間上東四今金九入学高円子外八六下来気小七山話女北午百書先名川千水半男西電校語土木聞食車何南万毎白天母火右読友左休父雨'},
    	{name:'N4', kanji:'会同事自社発者地業方新場員立開手力問代明動京目通言理体田主題意不作用度強公持野以思家世多正安院心界教文元重近考画海売知道集別物使品計死特私始朝運終台広住真有口少町料工建空急止送切転研足究楽起着店病質待試族銀早映親験英医仕去味写字答夜音注帰古歌買悪図週室歩風紙黒花春赤青館屋色走秋夏習駅洋旅服夕借曜飲肉貸堂鳥飯勉冬昼茶弟牛魚兄犬妹姉漢'},
    	{name:'N3', kanji:'政議民連対部合市内相定回選米実関決全表戦経最現調化当約首法性要制治務成期取都和機平加受続進数記初指権支産点報済活原共得解交資予向際勝面告反判認参利組信在件側任引求所次昨論官増係感情投示変打直両式確果容必演歳争談能位置流格疑過局放常状球職与供役構割費付由説難優夫収断石違消神番規術備宅害配警育席訪乗残想声念助労例然限追商葉伝働形景落好退頭負渡失差末守若種美命福望非観察段横深申様財港識呼達良候程満敗値突光路科積他処太客否師登易速存飛殺号単座破除完降責捕危給苦迎園具辞因馬愛富彼未舞亡冷適婦寄込顔類余王返妻背熱宿薬険頼覚船途許抜便留罪努精散静婚喜浮絶幸押倒等老曲払庭徒勤遅居雑招困欠更刻賛抱犯恐息遠戻願絵越欲痛笑互束似列探逃遊迷夢君閉緒折草暮酒悲晴掛到寝暗盗吸陽御歯忘雪吹娘誤洗慣礼窓昔貧怒祖泳杯疲皆鳴腹煙眠怖耳頂箱晩寒髪忙才靴恥偶偉猫幾'},
    	{name:'N2', kanji:'党協総区領県設改府査委軍団各島革村勢減再税営比防補境導副算輸述線農州武象域額欧担準賞辺造被技低復移個門課脳極含蔵量型況針専谷史階管兵接細効丸湾録省旧橋岸周材戸央券編捜竹超並療採森競介根販歴将幅般貿講林装諸劇河航鉄児禁印逆換久短油暴輪占植清倍均億圧芸署伸停爆陸玉波帯延羽固則乱普測豊厚齢囲卒略承順岩練軽了庁城患層版令角絡損募裏仏績築貨混昇池血温季星永著誌庫刊像香坂底布寺宇巨震希触依籍汚枚複郵仲栄札板骨傾届巻燃跡包駐弱紹雇替預焼簡章臓律贈照薄群秒奥詰双刺純翌快片敬悩泉皮漁荒貯硬埋柱祭袋筆訓浴童宝封胸砂塩賢腕兆床毛緑尊祝柔殿濃液衣肩零幼荷泊黄甘臣浅掃雲掘捨軟沈凍乳恋紅郊腰炭踊冊勇械菜珍卵湖喫干虫刷湯溶鉱涙匹孫鋭枝塗軒毒叫拝氷乾棒祈拾粉糸綿汗銅湿瓶咲召缶隻脂蒸肌耕鈍泥隅灯辛磨麦姓筒鼻粒詞胃畳膚机濯塔灰沸菓帽枯涼舟貝符憎皿肯燥畜挟曇滴伺'},
    	{name:'N1', kanji:'氏統保第結派案策基価提挙応企検藤沢裁証援施井護展態鮮視条幹独宮率衛張監環審義訴株姿閣衆評影松撃佐核整融製票渉響推請器士討攻崎督授催及憲離激摘系批郎健盟従修隊織拡故振弁就異献厳維浜遺塁邦素遣抗模雄益緊標宣昭廃伊江僚吉盛皇臨踏壊債興源儀創障継筋闘葬避司康善逮迫惑崩紀聴脱級博締救執房撤削密措志載陣我為抑幕染奈傷択秀徴弾償功拠秘拒刑塚致繰尾描鈴盤項喪伴養懸街契掲躍棄邸縮還属慮枠恵露沖緩節需射購揮充貢鹿却端賃獲郡併徹貴衝焦奪災浦析譲称納樹挑誘紛至宗促慎控智握宙俊銭渋銃操携診託撮誕侵括謝駆透津壁稲仮裂敏是排裕堅訳芝綱典賀扱顧弘看訟戒祉誉歓奏勧騒閥甲縄郷揺免既薦隣華範隠徳哲杉釈己妥威豪熊滞微隆症暫忠倉彦肝喚沿妙唱阿索誠襲懇俳柄驚麻李浩剤瀬趣陥斎貫仙慰序旬兼聖旨即柳舎偽較覇詳抵脅茂犠旗距雅飾網竜詩繁翼潟敵魅嫌斉敷擁圏酸滅罰礎腐脚潮梅尽僕桜滑孤炎賠句鋼頑鎖彩摩励縦輝蓄軸巡稼瞬砲噴誇祥牲秩帝宏唆阻泰賄撲堀菊絞縁唯膨矢耐塾漏慶猛芳懲剣彰棋丁恒揚冒之倫陳憶潜梨仁克岳概拘墓黙須偏雰遇諮狭卓亀糧簿炉牧殊殖艦輩穴奇慢鶴謀暖昌拍朗寛覆胞泣隔浄没暇肺貞靖鑑飼陰銘随烈尋稿丹啓也丘棟壌漫玄粘悟舗妊熟旭恩騰往豆遂狂岐陛緯培衰艇屈径淡抽披廷錦准暑磯奨浸剰胆繊駒虚霊帳悔諭惨虐翻墜沼据肥徐糖搭盾脈滝軌俵妨擦鯨荘諾雷漂懐勘栽拐駄添冠斜鏡聡浪亜覧詐壇勲魔酬紫曙紋卸奮欄逸涯拓眼獄尚彫穏顕巧矛垣欺釣萩粛栗愚嘉遭架鬼庶稚滋幻煮姫誓把践呈疎仰剛疾征砕謡嫁謙后嘆菌鎌巣頻琴班棚潔酷宰廊寂辰霞伏碁俗漠邪晶墨鎮洞履劣那殴娠奉憂朴亭淳怪鳩酔惜穫佳潤悼乏該赴桑桂髄虎盆晋穂壮堤飢傍疫累痴搬晃癒桐寸郭尿凶吐宴鷹賓虜陶鐘憾猪紘磁弥昆粗訂芽庄傘敦騎寧循忍怠如寮祐鵬鉛珠凝苗獣哀跳匠垂蛇澄縫僧眺亘呉凡憩媛溝恭刈睡錯伯笹穀陵霧魂弊妃舶餓窮掌麗綾臭悦刃縛暦宜盲粋辱毅轄猿弦稔窒炊洪摂飽冗桃狩朱渦紳枢碑鍛刀鼓裸猶塊旋弓幣膜扇腸槽慈楊伐駿漬糾亮墳坪紺娯椿舌羅峡俸厘峰圭醸蓮弔乙汁尼遍衡薫猟羊款閲偵喝敢胎酵憤豚遮扉硫赦窃泡瑞又慨紡恨肪扶戯伍忌濁奔斗蘭迅肖鉢朽殻享秦茅藩沙輔媒鶏禅嘱胴迭挿嵐椎絹陪剖譜郁悠淑帆暁傑楠笛玲奴錠拳翔遷拙侍尺峠篤肇渇叔雌亨堪叙酢吟逓嶺甚喬崇漆岬癖愉寅礁乃洲屯樺槙姻巌擬塀唇睦閑胡幽峻曹詠卑侮鋳抹尉槻隷禍蝶酪茎帥逝汽琢匿襟蛍蕉寡琉痢庸朋坑藍賊搾畔遼唄孔橘漱呂拷嬢苑巽杜渓翁廉謹瞳湧欣窯褒醜升殉煩巴禎劾堕租稜桟倭婿慕斐罷矯某囚魁虹鴻泌於赳漸蚊葵厄藻禄孟嫡尭嚇巳凸暢韻霜硝勅芹杏棺儒鳳馨慧愁楼彬匡眉欽薪褐賜嵯綜繕栓翠鮎榛凹艶惣蔦錬隼渚衷逐斥稀芙詔皐雛惟佑耀黛渥憧宵妄惇脩甫酌蚕嬉蒼暉頒只肢檀凱彗謄梓丑嗣叶汐絢朔伽畝抄爽黎惰蛮冴萌旺壱偲瑠允侯蒔鯉弧遥舜瑛附彪卯但綺芋茜凌皓洸毬婆緋鯛怜邑倣碧啄穣酉悌倹柚繭亦詢采紗賦眸玖弐錘諄倖痘笙侃裟洵爾耗昴銑莞伶碩宥滉晏伎朕迪綸且竣晨吏燦麿頌箇楓琳梧哉澪匁晟衿凪梢丙颯茄勺恕蕗瑚遵瞭燎虞柊侑謁斤嵩捺蓉茉袈燿誼冶栞墾勁菖旦椋叡紬胤凜亥爵脹麟莉汰瑶瑳耶椰絃丞璃奎塑昂柾熙菫諒鞠崚濫捷'}
    ];
    jlpt.kanji_details = {
        '丑': {meanings:['sign of the ox or cow','1-3AM','second sign of Chinese zodiac'], kunyomi:['うし'], onyomi:['チュウ']},
        '丙': {meanings:['third class','3rd','3rd calendar sign'], kunyomi:['ひのえ'], onyomi:['ヘイ']},
        '丞': {meanings:['help'], kunyomi:['すく','たす'], onyomi:['ジョウ','ショウ']},
        '亘': {meanings:['span','range','extend over'], kunyomi:['わた','もと'], onyomi:['コウ','カン','セン']},
        '亥': {meanings:['sign of the hog','9-11PM','twelfth sign of the Chinese zodiac'], kunyomi:['い'], onyomi:['ガイ','カイ']},
        '亦': {meanings:['also','again'], kunyomi:['また'], onyomi:['エキ','ヤク']},
        '亨': {meanings:['pass through','go smoothly'], kunyomi:['とお'], onyomi:['コウ','キョウ','ホウ']},
        '伍': {meanings:['five','five-man squad','file','line'], kunyomi:['いつつ'], onyomi:['ゴ']},
        '伶': {meanings:['actor'], kunyomi:['わざおぎ'], onyomi:['レイ','リョウ']},
        '伽': {meanings:['nursing','attending','entertainer'], kunyomi:['とぎ'], onyomi:['カ','ガ','キャ','ギャ']},
        '但': {meanings:['however','but'], kunyomi:['ただ'], onyomi:['タン']},
        '佑': {meanings:['help','assist'], kunyomi:['たす'], onyomi:['ユウ','ウ']},
        '侃': {meanings:['strong','just','righteous','peace-loving'], kunyomi:['つよ'], onyomi:['カン']},
        '侑': {meanings:['urge to eat'], kunyomi:['すす','たす'], onyomi:['ユウ','ウ']},
        '侯': {meanings:['marquis','lord','daimyo'], kunyomi:[''], onyomi:['コウ']},
        '倖': {meanings:['happiness','luck'], kunyomi:['しあわ','さいわ'], onyomi:['コウ']},
        '倣': {meanings:['emulate','imitate'], kunyomi:['なら'], onyomi:['ホウ']},
        '倭': {meanings:['Yamato','ancient Japan'], kunyomi:['やまと','したが'], onyomi:['ワ','イ']},
        '偲': {meanings:['recollect','remember'], kunyomi:['しの'], onyomi:['サイ','シ']},
        '儒': {meanings:['Confucian'], kunyomi:[''], onyomi:['ジュ']},
        '允': {meanings:['license','sincerity','permit'], kunyomi:['じょう','まこと','ゆるす'], onyomi:['イン']},
        '冴': {meanings:['be clear','serene','cold','skilful'], kunyomi:['さ','こお','ひ'], onyomi:['ゴ','コ']},
        '冶': {meanings:['melting','smelting'], kunyomi:['い'], onyomi:['ヤ']},
        '凜': {meanings:['cold','strict','severe'], kunyomi:['きびし'], onyomi:['リン']},
        '凪': {meanings:['lull','calm','(kokuji)'], kunyomi:['なぎ','な'], onyomi:['']},
        '凱': {meanings:['victory song'], kunyomi:['かちどき','やわらぐ'], onyomi:['ガイ','カイ']},
        '勁': {meanings:['strong'], kunyomi:['つよ'], onyomi:['ケイ']},
        '勅': {meanings:['imperial order'], kunyomi:['いまし','みことのり'], onyomi:['チョク']},
        '勺': {meanings:['ladle','one tenth of a go','dip'], kunyomi:[''], onyomi:['シャク']},
        '匁': {meanings:['monme','3.75 grams','(kokuji)'], kunyomi:['もんめ','め'], onyomi:['']},
        '匡': {meanings:['correct','save','assist'], kunyomi:['すく'], onyomi:['キョウ','オウ']},
        '卯': {meanings:['sign of the hare or rabbit','fourth sign of Chinese zodiac','5-7AM','east'], kunyomi:['う'], onyomi:['ボウ','モウ']},
        '厘': {meanings:['rin','1/10 sen','1/10 bu'], kunyomi:[''], onyomi:['リン']},
        '叡': {meanings:['intelligence','imperial'], kunyomi:['あき'], onyomi:['エイ']},
        '只': {meanings:['only','free','in addition'], kunyomi:['ただ'], onyomi:['シ']},
        '叶': {meanings:['grant','answer'], kunyomi:['かな','かな'], onyomi:['キョウ']},
        '吏': {meanings:['officer','an official'], kunyomi:[''], onyomi:['リ']},
        '啄': {meanings:['peck','pick up'], kunyomi:['ついば','つつ'], onyomi:['タク','ツク','トク']},
        '喬': {meanings:['high','boasting'], kunyomi:['たか'], onyomi:['キョウ']},
        '嗣': {meanings:['heir','succeed'], kunyomi:[''], onyomi:['シ']},
        '嚇': {meanings:['menacing','dignity','majesty','threaten'], kunyomi:['おど'], onyomi:['カク']},
        '圭': {meanings:['square jewel','corner','angle','edge'], kunyomi:[''], onyomi:['ケイ','ケ']},
        '塑': {meanings:['model','molding'], kunyomi:['でく'], onyomi:['ソ']},
        '墾': {meanings:['ground-breaking','open up farmland'], kunyomi:['は','ひら'], onyomi:['コン']},
        '壱': {meanings:['one (in documents)'], kunyomi:['ひとつ'], onyomi:['イチ','イツ']},
        '奎': {meanings:['star','god of literature'], kunyomi:[''], onyomi:['ケイ','キ']},
        '嫡': {meanings:['legitimate wife','direct descent (non-bastard)'], kunyomi:[''], onyomi:['チャク','テキ']},
        '嬉': {meanings:['glad','pleased','rejoice'], kunyomi:['うれ','たの'], onyomi:['キ']},
        '孟': {meanings:['chief','beginning'], kunyomi:['かしら'], onyomi:['モウ','ボウ','ミョウ']},
        '宏': {meanings:['wide','large'], kunyomi:['ひろ'], onyomi:['コウ']},
        '宥': {meanings:['soothe','calm','pacify'], kunyomi:['なだ','ゆる'], onyomi:['ユウ']},
        '宵': {meanings:['wee hours','evening','early night'], kunyomi:['よい'], onyomi:['ショウ']},
        '寅': {meanings:['sign of the tiger','3-5AM','third sign of Chinese zodiac'], kunyomi:['とら'], onyomi:['イン']},
        '尭': {meanings:['high','far'], kunyomi:['たか'], onyomi:['ギョウ']},
        '峻': {meanings:['high','steep'], kunyomi:['けわ','たか'], onyomi:['シュン']},
        '崚': {meanings:['mountains towering in a row'], kunyomi:[''], onyomi:['リョウ']},
        '嵩': {meanings:['be aggravated','grow worse','grow bulky','swell'], kunyomi:['かさ','かさ','たか'], onyomi:['スウ','シュウ']},
        '嵯': {meanings:['steep','craggy','rugged'], kunyomi:[''], onyomi:['サ','シ']},
        '嶺': {meanings:['peak','summit'], kunyomi:['みね'], onyomi:['レイ','リョウ']},
        '巌': {meanings:['rock','crag','boulder'], kunyomi:['いわ','いわお','けわ'], onyomi:['ガン']},
        '巳': {meanings:['sign of the snake or serpent','9-11AM','sixth sign of Chinese zodiac'], kunyomi:['み'], onyomi:['シ']},
        '巴': {meanings:['comma-design'], kunyomi:['ともえ','うずまき'], onyomi:['ハ']},
        '巽': {meanings:['southeast'], kunyomi:['たつみ'], onyomi:['ソン']},
        '弐': {meanings:['II','two','second'], kunyomi:['ふた','そえ'], onyomi:['ニ','ジ']},
        '弘': {meanings:['vast','broad','wide'], kunyomi:['ひろ'], onyomi:['コウ','グ']},
        '彗': {meanings:['comet'], kunyomi:['ほうき'], onyomi:['スイ','エ','ケイ','セイ']},
        '彦': {meanings:['lad','boy (ancient)'], kunyomi:['ひこ'], onyomi:['ゲン']},
        '彪': {meanings:['spotted','mottled','patterned','small tiger'], kunyomi:['あや'], onyomi:['ヒョウ','ヒュウ']},
        '彬': {meanings:['refined','gentle'], kunyomi:['うるわ','あき'], onyomi:['ヒン','フン']},
        '怜': {meanings:['wise'], kunyomi:['あわ','さと'], onyomi:['レイ','レン','リョウ']},
        '恕': {meanings:['excuse','tolerate','forgive'], kunyomi:['ゆる'], onyomi:['ジョ','ショ']},
        '悌': {meanings:['serving our elders'], kunyomi:[''], onyomi:['テイ','ダイ']},
        '惇': {meanings:['sincere','kind','considerate'], kunyomi:['あつ'], onyomi:['シュン','ジュン','トン']},
        '惟': {meanings:['consider','reflect','think'], kunyomi:['おも','これ','おも'], onyomi:['イ','ユイ']},
        '惣': {meanings:['all'], kunyomi:['すべ'], onyomi:['ソウ']},
        '愁': {meanings:['distress','grieve','lament','be anxious'], kunyomi:['うれ','うれ'], onyomi:['シュウ']},
        '慧': {meanings:['wise'], kunyomi:['さとい'], onyomi:['ケイ','エ']},
        '抄': {meanings:['extract','selection','summary','copy','spread thin'], kunyomi:[''], onyomi:['ショウ']},
        '捷': {meanings:['victory','fast'], kunyomi:['はや'], onyomi:['ショウ','ソウ']},
        '捺': {meanings:['press','print','affix a seal','stamp'], kunyomi:['さ','お'], onyomi:['ナツ','ダツ']},
        '敦': {meanings:['industry','kindliness'], kunyomi:['あつ'], onyomi:['トン','タイ','ダン','チョウ']},
        '斤': {meanings:['axe','1.32 lb','catty','counter for loaves of bread','axe radical (no. 69)'], kunyomi:[''], onyomi:['キン']},
        '斥': {meanings:['reject','retreat','recede','withdraw','repel','repulse'], kunyomi:['しりぞ'], onyomi:['セキ']},
        '於': {meanings:['at','in','on','as for'], kunyomi:['おい','お','ああ','より'], onyomi:['オ','ヨ']},
        '旭': {meanings:['rising sun','morning sun'], kunyomi:['あさひ'], onyomi:['キョク']},
        '旺': {meanings:['flourishing','successful','beautiful','vigorous'], kunyomi:['かがや','うつくし','さかん'], onyomi:['オウ','キョウ','ゴウ']},
        '昂': {meanings:['rise'], kunyomi:['あ','たか','たか'], onyomi:['コウ','ゴウ']},
        '昴': {meanings:['the Pleiades'], kunyomi:['すばる'], onyomi:['コウ','ボウ']},
        '晃': {meanings:['clear'], kunyomi:['あきらか'], onyomi:['コウ']},
        '晋': {meanings:['advance'], kunyomi:['すす'], onyomi:['シン']},
        '晏': {meanings:['late','quiet','sets (sun)'], kunyomi:['おそ'], onyomi:['アン']},
        '晟': {meanings:['clear'], kunyomi:['あきらか'], onyomi:['セイ','ジョウ']},
        '晨': {meanings:['morning','early'], kunyomi:['あした','とき','あさ'], onyomi:['シン']},
        '暉': {meanings:['shine','light'], kunyomi:['かが'], onyomi:['キ']},
        '暢': {meanings:['stretch'], kunyomi:['のび'], onyomi:['チョウ']},
        '朋': {meanings:['companion','friend'], kunyomi:['とも'], onyomi:['ホウ']},
        '朔': {meanings:['conjunction (astronomy)','first day of month','north'], kunyomi:['ついたち'], onyomi:['サク']},
        '朕': {meanings:['majestic plural','imperial we'], kunyomi:[''], onyomi:['チン']},
        '李': {meanings:['plum'], kunyomi:['すもも'], onyomi:['リ']},
        '杜': {meanings:['woods','grove'], kunyomi:['もり','ふさ','やまなし'], onyomi:['ト','トウ','ズ']},
        '柊': {meanings:['holly'], kunyomi:['ひいらぎ'], onyomi:['シュ','シュウ']},
        '柚': {meanings:['citron'], kunyomi:['ゆず'], onyomi:['ユ','ユウ','ジク']},
        '柾': {meanings:['straight grain','spindle tree','(kokuji)'], kunyomi:['まさ','まさめ','まさき'], onyomi:['']},
        '栗': {meanings:['chestnut'], kunyomi:['くり','おののく'], onyomi:['リツ','リ']},
        '桂': {meanings:['Japanese Judas-tree','cinnamon tree'], kunyomi:['かつら'], onyomi:['ケイ']},
        '桐': {meanings:['paulownia'], kunyomi:['きり'], onyomi:['トウ','ドウ']},
        '梢': {meanings:['treetops','twig'], kunyomi:['こずえ','くすのき'], onyomi:['ショウ']},
        '梧': {meanings:['Chinese parasol tree','phoenix tree'], kunyomi:['あおぎり'], onyomi:['ゴ']},
        '棺': {meanings:['coffin','casket'], kunyomi:[''], onyomi:['カン']},
        '椋': {meanings:['type of deciduous tree','grey starling'], kunyomi:['むく'], onyomi:['リョウ']},
        '椰': {meanings:['coconut tree'], kunyomi:['やし'], onyomi:['ヤ']},
        '椿': {meanings:['camellia'], kunyomi:['つばき'], onyomi:['チン','チュン']},
        '楊': {meanings:['willow'], kunyomi:['やなぎ'], onyomi:['ヨウ']},
        '楠': {meanings:['camphor tree'], kunyomi:['くす','くすのき'], onyomi:['ナン','ダン','ゼン','ネン']},
        '楼': {meanings:['watchtower','lookout','high building'], kunyomi:['たかどの'], onyomi:['ロウ']},
        '榛': {meanings:['hazelnut','filbert'], kunyomi:['はしばみ','はり'], onyomi:['シン','ハン']},
        '槙': {meanings:['twig','ornamental evergreen'], kunyomi:['まき','こずえ'], onyomi:['テン','シン']},
        '槻': {meanings:['Zelkova tree'], kunyomi:['つき'], onyomi:['キ']},
        '樺': {meanings:['birch','dark red'], kunyomi:['かば','かんば'], onyomi:['カ']},
        '橘': {meanings:['mandarin orange'], kunyomi:['たちばな'], onyomi:['キツ']},
        '檀': {meanings:['cedar','sandlewood','spindle tree'], kunyomi:['まゆみ'], onyomi:['ダン','タン']},
        '欣': {meanings:['take pleasure in','rejoice'], kunyomi:['よろこ','よろこ'], onyomi:['キン','ゴン','コン']},
        '欽': {meanings:['respect','revere','long for'], kunyomi:['つつし'], onyomi:['キン','コン']},
        '毅': {meanings:['strong'], kunyomi:['つよ'], onyomi:['キ','ギ']},
        '毬': {meanings:['burr','ball'], kunyomi:['いが','まり'], onyomi:['キュウ']},
        '汐': {meanings:['eventide','tide','salt water','opportunity'], kunyomi:['しお','うしお','せい'], onyomi:['セキ']},
        '洲': {meanings:['continent','sandbar','island','country'], kunyomi:['しま'], onyomi:['シュウ','ス']},
        '洵': {meanings:['alike','truth'], kunyomi:['の','まこと'], onyomi:['ジュン','シュン']},
        '洸': {meanings:['sparkling water'], kunyomi:[''], onyomi:['コウ']},
        '浩': {meanings:['wide expanse','abundance','vigorous'], kunyomi:['おおき','ひろ'], onyomi:['コウ']},
        '淳': {meanings:['pure'], kunyomi:['あつ'], onyomi:['ジュン','シュン']},
        '渚': {meanings:['strand','beach','shore'], kunyomi:['なぎさ'], onyomi:['ショ']},
        '渥': {meanings:['kindness','moisten'], kunyomi:['あつ','うるお'], onyomi:['アク']},
        '滉': {meanings:['deep and broad'], kunyomi:['ひろ'], onyomi:['コウ']},
        '漱': {meanings:['gargle','rinse mouth'], kunyomi:['くちすす','くちそそ','うがい','すす'], onyomi:['ソウ','シュウ','ス']},
        '澪': {meanings:['water route','shipping channel'], kunyomi:['みお'], onyomi:['レイ']},
        '濫': {meanings:['excessive','overflow','spread out'], kunyomi:['みだ','みだ'], onyomi:['ラン']},
        '熙': {meanings:['bright','sunny','prosperous','merry'], kunyomi:['たのし','ひか','ひろ','よろこ','かわ','あきらか','ひろ','ひろ'], onyomi:['キ']},
        '燎': {meanings:['burn','bonfire'], kunyomi:['かがりび'], onyomi:['リョウ']},
        '燦': {meanings:['brilliant'], kunyomi:['さん','あき','きらめ','きら'], onyomi:['サン']},
        '燿': {meanings:['shine'], kunyomi:['かがや','ひかり'], onyomi:['ヨウ']},
        '爵': {meanings:['baron','peerage','court rank'], kunyomi:[''], onyomi:['シャク']},
        '爾': {meanings:['you','thou','second person'], kunyomi:['なんじ','しかり','その','のみ','おれ','しか'], onyomi:['ジ','ニ']},
        '猪': {meanings:['boar'], kunyomi:['い','いのしし'], onyomi:['チョ']},
        '玖': {meanings:['beautiful black jewel','nine'], kunyomi:[''], onyomi:['キュウ','ク']},
        '玲': {meanings:['sound of jewels'], kunyomi:[''], onyomi:['レイ']},
        '琉': {meanings:['precious stone','gem','lapis lazuli'], kunyomi:[''], onyomi:['リュウ','ル']},
        '琢': {meanings:['polish'], kunyomi:['みが'], onyomi:['タク']},
        '琳': {meanings:['jewel','tinkling of jewelry'], kunyomi:[''], onyomi:['リン']},
        '瑚': {meanings:['ancestral offering receptacle','coral'], kunyomi:[''], onyomi:['コ','ゴ']},
        '瑳': {meanings:['polish','brilliant white luster of a gem','artful smile'], kunyomi:['みが'], onyomi:['サ']},
        '瑶': {meanings:['beautiful as a jewel'], kunyomi:['たま'], onyomi:['ヨウ']},
        '甫': {meanings:['for the first time','not until'], kunyomi:['はじ'], onyomi:['ホ','フ']},
        '畝': {meanings:['furrow','thirty tsubo','ridge','rib'], kunyomi:['せ','うね'], onyomi:['ボウ','ホ','モ','ム']},
        '痘': {meanings:['pox','smallpox'], kunyomi:[''], onyomi:['トウ']},
        '皐': {meanings:['swamp','shore'], kunyomi:['さつき'], onyomi:['コウ']},
        '皓': {meanings:['white','clear'], kunyomi:['しろ','ひか'], onyomi:['コウ']},
        '眉': {meanings:['eyebrow'], kunyomi:['まゆ'], onyomi:['ビ','ミ']},
        '眸': {meanings:['pupil of the eye'], kunyomi:['ひとみ'], onyomi:['ボウ','ム']},
        '硝': {meanings:['nitrate','saltpeter'], kunyomi:[''], onyomi:['ショウ']},
        '碧': {meanings:['blue','green'], kunyomi:[''], onyomi:['ヘキ','ヒャク']},
        '碩': {meanings:['large','great','eminent'], kunyomi:['おお'], onyomi:['セキ']},
        '磯': {meanings:['seashore','beach'], kunyomi:['いそ'], onyomi:['キ']},
        '祐': {meanings:['help'], kunyomi:['たす'], onyomi:['ユウ','ウ']},
        '禄': {meanings:['fief','allowance','pension','grant','happiness'], kunyomi:['さいわ','ふち'], onyomi:['ロク']},
        '禎': {meanings:['happiness','blessed','good fortune','auspicious'], kunyomi:['さいわ'], onyomi:['テイ']},
        '秦': {meanings:['Manchu dynasty','name given to naturalized foreigners'], kunyomi:['はた'], onyomi:['シン']},
        '稀': {meanings:['rare','phenomenal','dilute (acid)'], kunyomi:['まれ','まばら'], onyomi:['キ','ケ']},
        '稔': {meanings:['harvest','ripen'], kunyomi:['みの','みのり'], onyomi:['ネン','ジン','ニン']},
        '稜': {meanings:['angle','edge','corner','power','majesty'], kunyomi:['いつ','かど'], onyomi:['リョウ','ロウ']},
        '穣': {meanings:['good crops','prosperity','10**28'], kunyomi:['わら','ゆたか'], onyomi:['ジョウ']},
        '窯': {meanings:['kiln','oven','furnace'], kunyomi:['かま'], onyomi:['ヨウ']},
        '竣': {meanings:['end','finish'], kunyomi:['わらわ','わらべ','おわ'], onyomi:['ドウ','シュン']},
        '笙': {meanings:['a reed instrument'], kunyomi:['ふえ'], onyomi:['ショウ','ソウ']},
        '笹': {meanings:['bamboo grass','(kokuji)'], kunyomi:['ささ'], onyomi:['']},
        '箇': {meanings:['counter for articles'], kunyomi:[''], onyomi:['カ','コ']},
        '紗': {meanings:['gauze','gossamer'], kunyomi:['うすぎぬ'], onyomi:['サ','シャ']},
        '紘': {meanings:['large'], kunyomi:['おおづな','つな','つなぐ'], onyomi:['コウ']},
        '紬': {meanings:['pongee (a knotted silk cloth)'], kunyomi:['つむぎ','つむ'], onyomi:['チュウ']},
        '絃': {meanings:['string','cord','samisen music'], kunyomi:['いと'], onyomi:['ゲン']},
        '絢': {meanings:['brilliant fabric design'], kunyomi:[''], onyomi:['ケン']},
        '綜': {meanings:['rule','synthesize'], kunyomi:['おさ','す'], onyomi:['ソウ']},
        '綸': {meanings:['thread','silk cloth'], kunyomi:['いと'], onyomi:['リン','カン']},
        '繕': {meanings:['darning','repair','mend','trim','tidy up','adjust'], kunyomi:['つくろ'], onyomi:['ゼン']},
        '繭': {meanings:['cocoon'], kunyomi:['まゆ','きぬ'], onyomi:['ケン']},
        '翁': {meanings:['venerable old man'], kunyomi:['おきな'], onyomi:['オウ']},
        '翠': {meanings:['green','kingfisher'], kunyomi:['かわせみ','みどり'], onyomi:['スイ']},
        '耀': {meanings:['shine','sparkle','gleam','twinkle'], kunyomi:['かがや','ひかり'], onyomi:['ヨウ']},
        '耗': {meanings:['decrease'], kunyomi:[''], onyomi:['モウ','コウ']},
        '耶': {meanings:['question mark'], kunyomi:['か'], onyomi:['ヤ','ジャ']},
        '肇': {meanings:['beginning'], kunyomi:['はじ','はじめ'], onyomi:['チョウ','ジョウ','トウ']},
        '肢': {meanings:['limb','arms & legs'], kunyomi:[''], onyomi:['シ']},
        '胤': {meanings:['descendent','issue','offspring'], kunyomi:['たね'], onyomi:['イン']},
        '脩': {meanings:['dried meat'], kunyomi:['おさ','なが','ほじし'], onyomi:['シュウ']},
        '脹': {meanings:['dilate','distend','bulge','fill out','swell'], kunyomi:['は','ふく','ふく'], onyomi:['チョウ']},
        '舜': {meanings:['type of morning glory','rose of Sharon','althea'], kunyomi:[''], onyomi:['シュン']},
        '艶': {meanings:['glossy','luster','glaze','polish','charm','colorful','captivating'], kunyomi:['つや','なま','あで','つや','なま'], onyomi:['エン']},
        '芙': {meanings:['lotus','Mt Fuji'], kunyomi:[''], onyomi:['フ']},
        '芹': {meanings:['parsley'], kunyomi:['せり'], onyomi:['キン']},
        '苑': {meanings:['garden','farm','park'], kunyomi:['その','う'], onyomi:['エン','オン']},
        '茄': {meanings:['eggplant'], kunyomi:[''], onyomi:['カ']},
        '茅': {meanings:['miscanthus reed'], kunyomi:['かや','ちがや'], onyomi:['ボウ','ミョウ']},
        '茉': {meanings:['jasmine'], kunyomi:[''], onyomi:['マツ','バツ','マ']},
        '莞': {meanings:['smiling','reed used to cover tatami'], kunyomi:['い'], onyomi:['カン']},
        '菖': {meanings:['iris'], kunyomi:[''], onyomi:['ショウ']},
        '菫': {meanings:['the violet'], kunyomi:['すみれ'], onyomi:['キン']},
        '萩': {meanings:['bush clover'], kunyomi:['はぎ'], onyomi:['シュウ']},
        '蒔': {meanings:['sow (seeds)'], kunyomi:['う','ま'], onyomi:['シ','ジ']},
        '蓉': {meanings:['lotus'], kunyomi:[''], onyomi:['ヨウ']},
        '蔦': {meanings:['vine','ivy'], kunyomi:['つた'], onyomi:['チョウ']},
        '蕉': {meanings:['banana','plantain'], kunyomi:[''], onyomi:['ショウ']},
        '蕗': {meanings:['butterbur','bog rhubarb'], kunyomi:['ふき'], onyomi:['ロ','ル']},
        '薪': {meanings:['fuel','firewood','kindling'], kunyomi:['たきぎ','まき'], onyomi:['シン']},
        '薫': {meanings:['send forth fragrance','fragrant','be scented','smoke (tobacco)'], kunyomi:['かお'], onyomi:['クン']},
        '蘭': {meanings:['orchid','Holland'], kunyomi:[''], onyomi:['ラン','ラ']},
        '虞': {meanings:['fear','uneasiness','anxiety','concern','expectation','consideration'], kunyomi:['おそれ','おもんぱか','はか','うれ','あざむ','あやま','のぞ','たの'], onyomi:['グ']},
        '蚕': {meanings:['silkworm'], kunyomi:['かいこ','こ'], onyomi:['サン','テン']},
        '衷': {meanings:['inmost','heart','mind','inside'], kunyomi:[''], onyomi:['チュウ']},
        '衿': {meanings:['neck','collar','lapel'], kunyomi:['えり'], onyomi:['キン','コン']},
        '袈': {meanings:['a coarse camlet'], kunyomi:[''], onyomi:['ケ','カ']},
        '裟': {meanings:['Buddhist surplice'], kunyomi:[''], onyomi:['サ','シャ']},
        '褐': {meanings:['brown','woollen kimono'], kunyomi:[''], onyomi:['カツ']},
        '詔': {meanings:['imperial edict'], kunyomi:['みことのり'], onyomi:['ショウ']},
        '詢': {meanings:['consult with'], kunyomi:['はか','まこと'], onyomi:['ジュン','シュン']},
        '誼': {meanings:['friendship','intimacy'], kunyomi:['よしみ','よい'], onyomi:['ギ']},
        '諄': {meanings:['tedious'], kunyomi:['ひちくど','くど','くどくど','ねんご'], onyomi:['シュン']},
        '謁': {meanings:['audience','audience (with king)'], kunyomi:[''], onyomi:['エツ']},
        '謄': {meanings:['mimeograph','copy'], kunyomi:[''], onyomi:['トウ']},
        '賜': {meanings:['grant','gift','boon','results'], kunyomi:['たまわ','たま','たも'], onyomi:['シ']},
        '賦': {meanings:['levy','ode','prose','poem','tribute','installment'], kunyomi:[''], onyomi:['フ','ブ']},
        '赳': {meanings:['strong and brave'], kunyomi:[''], onyomi:['キュウ']},
        '辰': {meanings:['sign of the dragon','7-9AM','fifth sign of Chinese zodiac','shin dragon radical (no. 161)'], kunyomi:['たつ'], onyomi:['シン','ジン']},
        '迪': {meanings:['edify','way','path'], kunyomi:['みち','みちび','すす','いた'], onyomi:['テキ']},
        '逐': {meanings:['pursue','drive away','chase','accomplish','attain','commit'], kunyomi:[''], onyomi:['チク']},
        '逓': {meanings:['relay','in turn','sending'], kunyomi:['かわ','たがいに'], onyomi:['テイ']},
        '遵': {meanings:['abide by','follow','obey','learn'], kunyomi:[''], onyomi:['ジュン']},
        '邑': {meanings:['village','rural community','right village radical (no. 163)'], kunyomi:['むら'], onyomi:['ユウ']},
        '郁': {meanings:['cultural progress','perfume'], kunyomi:[''], onyomi:['イク']},
        '酉': {meanings:['west','bird','sign of the bird','5-7PM','tenth sign of Chinese zodiac','sake radical (no. 164)'], kunyomi:['とり'], onyomi:['ユウ']},
        '采': {meanings:['dice','form','appearance','take','gather','coloring'], kunyomi:['と','いろどり'], onyomi:['サイ']},
        '銑': {meanings:['pig iron'], kunyomi:[''], onyomi:['セン']},
        '錘': {meanings:['weight','plumb bob','sinker','spindle'], kunyomi:['つむ','おもり'], onyomi:['スイ']},
        '附': {meanings:['affixed','attach','refer to','append'], kunyomi:['つ','つ'], onyomi:['フ']},
        '雛': {meanings:['chick','squab','duckling','doll'], kunyomi:['ひな','ひよこ'], onyomi:['スウ','ス','ジュ']},
        '霞': {meanings:['be hazy','grow dim','blurred'], kunyomi:['かすみ','かす'], onyomi:['カ','ゲ']},
        '鞠': {meanings:['ball'], kunyomi:['まり'], onyomi:['キク','キュウ']},
        '韻': {meanings:['rhyme','elegance','tone'], kunyomi:[''], onyomi:['イン']},
        '頌': {meanings:['eulogy'], kunyomi:['かたち','たた','ほめ'], onyomi:['ショウ','ジュ','ヨウ']},
        '頒': {meanings:['distribute','disseminate','partition','understand'], kunyomi:['わか'], onyomi:['ハン']},
        '馨': {meanings:['fragrant','balmy','favourable'], kunyomi:['かお','かおり'], onyomi:['ケイ','キョウ']},
        '魁': {meanings:['charging ahead of others'], kunyomi:['さきがけ','かしら'], onyomi:['カイ']},
        '鮎': {meanings:['freshwater trout','smelt'], kunyomi:['あゆ','なまず'], onyomi:['デン','ネン']},
        '鯛': {meanings:['sea bream','red snapper'], kunyomi:['たい'], onyomi:['チョウ']},
        '鳳': {meanings:['male mythical bird'], kunyomi:[''], onyomi:['ホウ','フウ']},
        '鴻': {meanings:['large bird','wild goose','large','great','powerful','prosperous'], kunyomi:['おおとり','ひしくい','おおがり'], onyomi:['コウ','ゴウ']},
        '鵬': {meanings:['phoenix'], kunyomi:['おおとり'], onyomi:['ホウ']},
        '鷹': {meanings:['hawk'], kunyomi:['たか'], onyomi:['ヨウ','オウ']},
        '麟': {meanings:['Chinese unicorn','genius','giraffe','bright','shining'], kunyomi:[''], onyomi:['リン']},
        '麿': {meanings:['I','you','(kokuji)'], kunyomi:['まろ'], onyomi:['']},
        '黎': {meanings:['dark','black','many'], kunyomi:['くろ'], onyomi:['レイ','リ']},
        '黛': {meanings:['blackened eyebrows'], kunyomi:['まゆずみ'], onyomi:['タイ']},
    };

    wkof.set_state('wkof.jlpt.kanji', 'ready');

})(window);

